package com.jc.pico.bean;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.Date;

@JsonIgnoreProperties(ignoreUnknown = true)
public class BaseBcode {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_base_bcode.BASE_CD
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    private String baseCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_base_bcode.MAIN_CD
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    private String mainCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_base_bcode.SUB_CD
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    private String subCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_base_bcode.TITLE
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_base_bcode.ORD_SQ
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    private Integer ordSq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_base_bcode.USE_YN
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    private Boolean useYn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_base_bcode.OLD_CD
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    private String oldCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_base_bcode.ALIAS
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    private String alias;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_base_bcode.DSC
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    private String dsc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_base_bcode.CID
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    private Integer cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_base_bcode.CDT
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    private Date cdt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_base_bcode.MID
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    private Integer mid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_base_bcode.MDT
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    private Date mdt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_base_bcode.CREATED
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_base_bcode.UPDATED
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    private Date updated;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_base_bcode.BASE_CD
     *
     * @return the value of tb_base_bcode.BASE_CD
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    public String getBaseCd() {
        return baseCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_base_bcode.BASE_CD
     *
     * @param baseCd the value for tb_base_bcode.BASE_CD
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    public void setBaseCd(String baseCd) {
        this.baseCd = baseCd == null ? null : baseCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_base_bcode.MAIN_CD
     *
     * @return the value of tb_base_bcode.MAIN_CD
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    public String getMainCd() {
        return mainCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_base_bcode.MAIN_CD
     *
     * @param mainCd the value for tb_base_bcode.MAIN_CD
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    public void setMainCd(String mainCd) {
        this.mainCd = mainCd == null ? null : mainCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_base_bcode.SUB_CD
     *
     * @return the value of tb_base_bcode.SUB_CD
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    public String getSubCd() {
        return subCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_base_bcode.SUB_CD
     *
     * @param subCd the value for tb_base_bcode.SUB_CD
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    public void setSubCd(String subCd) {
        this.subCd = subCd == null ? null : subCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_base_bcode.TITLE
     *
     * @return the value of tb_base_bcode.TITLE
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_base_bcode.TITLE
     *
     * @param title the value for tb_base_bcode.TITLE
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_base_bcode.ORD_SQ
     *
     * @return the value of tb_base_bcode.ORD_SQ
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    public Integer getOrdSq() {
        return ordSq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_base_bcode.ORD_SQ
     *
     * @param ordSq the value for tb_base_bcode.ORD_SQ
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    public void setOrdSq(Integer ordSq) {
        this.ordSq = ordSq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_base_bcode.USE_YN
     *
     * @return the value of tb_base_bcode.USE_YN
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    public Boolean getUseYn() {
        return useYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_base_bcode.USE_YN
     *
     * @param useYn the value for tb_base_bcode.USE_YN
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    public void setUseYn(Boolean useYn) {
        this.useYn = useYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_base_bcode.OLD_CD
     *
     * @return the value of tb_base_bcode.OLD_CD
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    public String getOldCd() {
        return oldCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_base_bcode.OLD_CD
     *
     * @param oldCd the value for tb_base_bcode.OLD_CD
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    public void setOldCd(String oldCd) {
        this.oldCd = oldCd == null ? null : oldCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_base_bcode.ALIAS
     *
     * @return the value of tb_base_bcode.ALIAS
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    public String getAlias() {
        return alias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_base_bcode.ALIAS
     *
     * @param alias the value for tb_base_bcode.ALIAS
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    public void setAlias(String alias) {
        this.alias = alias == null ? null : alias.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_base_bcode.DSC
     *
     * @return the value of tb_base_bcode.DSC
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    public String getDsc() {
        return dsc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_base_bcode.DSC
     *
     * @param dsc the value for tb_base_bcode.DSC
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    public void setDsc(String dsc) {
        this.dsc = dsc == null ? null : dsc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_base_bcode.CID
     *
     * @return the value of tb_base_bcode.CID
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_base_bcode.CID
     *
     * @param cid the value for tb_base_bcode.CID
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_base_bcode.CDT
     *
     * @return the value of tb_base_bcode.CDT
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    public Date getCdt() {
        return cdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_base_bcode.CDT
     *
     * @param cdt the value for tb_base_bcode.CDT
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    public void setCdt(Date cdt) {
        this.cdt = cdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_base_bcode.MID
     *
     * @return the value of tb_base_bcode.MID
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    public Integer getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_base_bcode.MID
     *
     * @param mid the value for tb_base_bcode.MID
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    public void setMid(Integer mid) {
        this.mid = mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_base_bcode.MDT
     *
     * @return the value of tb_base_bcode.MDT
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    public Date getMdt() {
        return mdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_base_bcode.MDT
     *
     * @param mdt the value for tb_base_bcode.MDT
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    public void setMdt(Date mdt) {
        this.mdt = mdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_base_bcode.CREATED
     *
     * @return the value of tb_base_bcode.CREATED
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_base_bcode.CREATED
     *
     * @param created the value for tb_base_bcode.CREATED
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_base_bcode.UPDATED
     *
     * @return the value of tb_base_bcode.UPDATED
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    public Date getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_base_bcode.UPDATED
     *
     * @param updated the value for tb_base_bcode.UPDATED
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
}