package com.jc.pico.bean;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.Date;

@JsonIgnoreProperties(ignoreUnknown = true)
public class SvcItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_svc_item.ID
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     * 
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_svc_item.CAT_ID
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    private Long catId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_svc_item.BRAND_ID
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    private Long brandId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_svc_item.STORE_ID
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    private Long storeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_svc_item.STATUS
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_svc_item.ITEM_TP
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    private String itemTp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_svc_item.ITEM_CD
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    private String itemCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_svc_item.BARCODE
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    private String barcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_svc_item.NAME
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_svc_item.SHORT_NAME
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    private String shortName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_svc_item.PRICE
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_svc_item.SUPPLY_PRICE
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    private Double supplyPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_svc_item.PURCHASE_PRICE
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    private Double purchasePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_svc_item.TAX
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    private Double tax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_svc_item.DISCOUNT_PRICE
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    private Double discountPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_svc_item.SERVICE_CHARGE
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    private Double serviceCharge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_svc_item.IS_TAX_INCLUDED
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    private Boolean isTaxIncluded;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_svc_item.TAX_TP
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    private String taxTp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_svc_item.IS_TIP_INCLUDED
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    private Boolean isTipIncluded;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_svc_item.IS_REWARD
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    private Boolean isReward;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_svc_item.IS_DISCOUNTABLE
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    private Boolean isDiscountable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_svc_item.IS_OPT_USED
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    private Boolean isOptUsed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_svc_item.IS_PACKABLE
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    private Boolean isPackable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_svc_item.IS_STAMP
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    private Boolean isStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_svc_item.MB_ICON_TP
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    private String mbIconTp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_svc_item.SALES_BEGIN
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    private String salesBegin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_svc_item.SALES_END
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    private String salesEnd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_svc_item.PRINTER_NO
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    private String printerNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_svc_item.ADMIN_ID
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    private String adminId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_svc_item.CREATED
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_svc_item.UPDATED
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    private Date updated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_svc_item.INTRO
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    private String intro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_svc_item.IS_STOCK_USE
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    private Boolean isStockUse;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_svc_item.SAFE_STOCK_CNT
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    private String safeStockCnt;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_svc_item.RECIPE
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    private String recipe;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_svc_item.ID
     *
     * @return the value of tb_svc_item.ID
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    
    private String isSoldOut;
    
    private String isDetailedDescription;
    private String isDetailedType;
    private String isDetailedContents;
    
    private String salesTimeBegin;
    
    private String salesTimeEnd;
    
    
    /* getter & setter */
    
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_svc_item.ID
     *
     * @param id the value for tb_svc_item.ID
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_svc_item.CAT_ID
     *
     * @return the value of tb_svc_item.CAT_ID
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    public Long getCatId() {
        return catId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_svc_item.CAT_ID
     *
     * @param catId the value for tb_svc_item.CAT_ID
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    public void setCatId(Long catId) {
        this.catId = catId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_svc_item.BRAND_ID
     *
     * @return the value of tb_svc_item.BRAND_ID
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    public Long getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_svc_item.BRAND_ID
     *
     * @param brandId the value for tb_svc_item.BRAND_ID
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    public void setBrandId(Long brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_svc_item.STORE_ID
     *
     * @return the value of tb_svc_item.STORE_ID
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    public Long getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_svc_item.STORE_ID
     *
     * @param storeId the value for tb_svc_item.STORE_ID
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    public void setStoreId(Long storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_svc_item.STATUS
     *
     * @return the value of tb_svc_item.STATUS
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_svc_item.STATUS
     *
     * @param status the value for tb_svc_item.STATUS
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_svc_item.ITEM_TP
     *
     * @return the value of tb_svc_item.ITEM_TP
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    public String getItemTp() {
        return itemTp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_svc_item.ITEM_TP
     *
     * @param itemTp the value for tb_svc_item.ITEM_TP
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    public void setItemTp(String itemTp) {
        this.itemTp = itemTp == null ? null : itemTp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_svc_item.ITEM_CD
     *
     * @return the value of tb_svc_item.ITEM_CD
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    public String getItemCd() {
        return itemCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_svc_item.ITEM_CD
     *
     * @param itemCd the value for tb_svc_item.ITEM_CD
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    public void setItemCd(String itemCd) {
        this.itemCd = itemCd == null ? null : itemCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_svc_item.BARCODE
     *
     * @return the value of tb_svc_item.BARCODE
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    public String getBarcode() {
        return barcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_svc_item.BARCODE
     *
     * @param barcode the value for tb_svc_item.BARCODE
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    public void setBarcode(String barcode) {
        this.barcode = barcode == null ? null : barcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_svc_item.NAME
     *
     * @return the value of tb_svc_item.NAME
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_svc_item.NAME
     *
     * @param name the value for tb_svc_item.NAME
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_svc_item.SHORT_NAME
     *
     * @return the value of tb_svc_item.SHORT_NAME
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    public String getShortName() {
        return shortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_svc_item.SHORT_NAME
     *
     * @param shortName the value for tb_svc_item.SHORT_NAME
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    public void setShortName(String shortName) {
        this.shortName = shortName == null ? null : shortName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_svc_item.PRICE
     *
     * @return the value of tb_svc_item.PRICE
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_svc_item.PRICE
     *
     * @param price the value for tb_svc_item.PRICE
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_svc_item.SUPPLY_PRICE
     *
     * @return the value of tb_svc_item.SUPPLY_PRICE
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    public Double getSupplyPrice() {
        return supplyPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_svc_item.SUPPLY_PRICE
     *
     * @param supplyPrice the value for tb_svc_item.SUPPLY_PRICE
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    public void setSupplyPrice(Double supplyPrice) {
        this.supplyPrice = supplyPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_svc_item.PURCHASE_PRICE
     *
     * @return the value of tb_svc_item.PURCHASE_PRICE
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    public Double getPurchasePrice() {
        return purchasePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_svc_item.PURCHASE_PRICE
     *
     * @param purchasePrice the value for tb_svc_item.PURCHASE_PRICE
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    public void setPurchasePrice(Double purchasePrice) {
        this.purchasePrice = purchasePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_svc_item.TAX
     *
     * @return the value of tb_svc_item.TAX
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    public Double getTax() {
        return tax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_svc_item.TAX
     *
     * @param tax the value for tb_svc_item.TAX
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    public void setTax(Double tax) {
        this.tax = tax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_svc_item.DISCOUNT_PRICE
     *
     * @return the value of tb_svc_item.DISCOUNT_PRICE
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    public Double getDiscountPrice() {
        return discountPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_svc_item.DISCOUNT_PRICE
     *
     * @param discountPrice the value for tb_svc_item.DISCOUNT_PRICE
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    public void setDiscountPrice(Double discountPrice) {
        this.discountPrice = discountPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_svc_item.SERVICE_CHARGE
     *
     * @return the value of tb_svc_item.SERVICE_CHARGE
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    public Double getServiceCharge() {
        return serviceCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_svc_item.SERVICE_CHARGE
     *
     * @param serviceCharge the value for tb_svc_item.SERVICE_CHARGE
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    public void setServiceCharge(Double serviceCharge) {
        this.serviceCharge = serviceCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_svc_item.IS_TAX_INCLUDED
     *
     * @return the value of tb_svc_item.IS_TAX_INCLUDED
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    public Boolean getIsTaxIncluded() {
        return isTaxIncluded;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_svc_item.IS_TAX_INCLUDED
     *
     * @param isTaxIncluded the value for tb_svc_item.IS_TAX_INCLUDED
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    public void setIsTaxIncluded(Boolean isTaxIncluded) {
        this.isTaxIncluded = isTaxIncluded;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_svc_item.TAX_TP
     *
     * @return the value of tb_svc_item.TAX_TP
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    public String getTaxTp() {
        return taxTp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_svc_item.TAX_TP
     *
     * @param taxTp the value for tb_svc_item.TAX_TP
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    public void setTaxTp(String taxTp) {
        this.taxTp = taxTp == null ? null : taxTp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_svc_item.IS_TIP_INCLUDED
     *
     * @return the value of tb_svc_item.IS_TIP_INCLUDED
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    public Boolean getIsTipIncluded() {
        return isTipIncluded;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_svc_item.IS_TIP_INCLUDED
     *
     * @param isTipIncluded the value for tb_svc_item.IS_TIP_INCLUDED
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    public void setIsTipIncluded(Boolean isTipIncluded) {
        this.isTipIncluded = isTipIncluded;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_svc_item.IS_REWARD
     *
     * @return the value of tb_svc_item.IS_REWARD
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    public Boolean getIsReward() {
        return isReward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_svc_item.IS_REWARD
     *
     * @param isReward the value for tb_svc_item.IS_REWARD
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    public void setIsReward(Boolean isReward) {
        this.isReward = isReward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_svc_item.IS_DISCOUNTABLE
     *
     * @return the value of tb_svc_item.IS_DISCOUNTABLE
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    public Boolean getIsDiscountable() {
        return isDiscountable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_svc_item.IS_DISCOUNTABLE
     *
     * @param isDiscountable the value for tb_svc_item.IS_DISCOUNTABLE
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    public void setIsDiscountable(Boolean isDiscountable) {
        this.isDiscountable = isDiscountable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_svc_item.IS_OPT_USED
     *
     * @return the value of tb_svc_item.IS_OPT_USED
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    public Boolean getIsOptUsed() {
        return isOptUsed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_svc_item.IS_OPT_USED
     *
     * @param isOptUsed the value for tb_svc_item.IS_OPT_USED
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    public void setIsOptUsed(Boolean isOptUsed) {
        this.isOptUsed = isOptUsed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_svc_item.IS_PACKABLE
     *
     * @return the value of tb_svc_item.IS_PACKABLE
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    public Boolean getIsPackable() {
        return isPackable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_svc_item.IS_PACKABLE
     *
     * @param isPackable the value for tb_svc_item.IS_PACKABLE
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    public void setIsPackable(Boolean isPackable) {
        this.isPackable = isPackable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_svc_item.IS_STAMP
     *
     * @return the value of tb_svc_item.IS_STAMP
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    public Boolean getIsStamp() {
        return isStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_svc_item.IS_STAMP
     *
     * @param isStamp the value for tb_svc_item.IS_STAMP
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    public void setIsStamp(Boolean isStamp) {
        this.isStamp = isStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_svc_item.MB_ICON_TP
     *
     * @return the value of tb_svc_item.MB_ICON_TP
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    public String getMbIconTp() {
        return mbIconTp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_svc_item.MB_ICON_TP
     *
     * @param mbIconTp the value for tb_svc_item.MB_ICON_TP
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    public void setMbIconTp(String mbIconTp) {
        this.mbIconTp = mbIconTp == null ? null : mbIconTp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_svc_item.SALES_BEGIN
     *
     * @return the value of tb_svc_item.SALES_BEGIN
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    public String getSalesBegin() {
        return salesBegin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_svc_item.SALES_BEGIN
     *
     * @param salesBegin the value for tb_svc_item.SALES_BEGIN
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    public void setSalesBegin(String salesBegin) {
        this.salesBegin = salesBegin == null ? null : salesBegin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_svc_item.SALES_END
     *
     * @return the value of tb_svc_item.SALES_END
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    public String getSalesEnd() {
        return salesEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_svc_item.SALES_END
     *
     * @param salesEnd the value for tb_svc_item.SALES_END
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    public void setSalesEnd(String salesEnd) {
        this.salesEnd = salesEnd == null ? null : salesEnd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_svc_item.PRINTER_NO
     *
     * @return the value of tb_svc_item.PRINTER_NO
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    public String getPrinterNo() {
        return printerNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_svc_item.PRINTER_NO
     *
     * @param printerNo the value for tb_svc_item.PRINTER_NO
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    public void setPrinterNo(String printerNo) {
        this.printerNo = printerNo == null ? null : printerNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_svc_item.ADMIN_ID
     *
     * @return the value of tb_svc_item.ADMIN_ID
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    public String getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_svc_item.ADMIN_ID
     *
     * @param adminId the value for tb_svc_item.ADMIN_ID
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    public void setAdminId(String adminId) {
        this.adminId = adminId == null ? null : adminId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_svc_item.CREATED
     *
     * @return the value of tb_svc_item.CREATED
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_svc_item.CREATED
     *
     * @param created the value for tb_svc_item.CREATED
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_svc_item.UPDATED
     *
     * @return the value of tb_svc_item.UPDATED
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    public Date getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_svc_item.UPDATED
     *
     * @param updated the value for tb_svc_item.UPDATED
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_svc_item.INTRO
     *
     * @return the value of tb_svc_item.INTRO
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    public String getIntro() {
        return intro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_svc_item.INTRO
     *
     * @param intro the value for tb_svc_item.INTRO
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    public void setIntro(String intro) {
        this.intro = intro == null ? null : intro.trim();
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_svc_item.IS_STOCK_USE
     *
     * @return the value of tb_svc_item.IS_STOCK_USE
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    public Boolean getIsStockUse() {
        return isStockUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_svc_item.IS_STOCK_USE
     *
     * @param isStamp the value for tb_svc_item.IS_STOCK_USE
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    public void setIsStockUse(Boolean isStockUse) {
        this.isStockUse = isStockUse;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_svc_item.SAFE_STOCK_CNT
     *
     * @return the value of tb_svc_item.SAFE_STOCK_CNT
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    public String getSafeStockCnt() {
        return safeStockCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_svc_item.SAFE_STOCK_CNT
     *
     * @param intro the value for tb_svc_item.SAFE_STOCK_CNT
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    public void setSafeStockCnt(String safeStockCnt) {
        this.safeStockCnt = safeStockCnt == null ? null : safeStockCnt.trim();
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_svc_item.RECIPE
     *
     * @return the value of tb_svc_item.RECIPE
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    public String getRecipe() {
        return recipe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_svc_item.RECIPE
     *
     * @param intro the value for tb_svc_item.RECIPE
     *
     * @mbggenerated Fri Sep 23 19:04:40 KST 2016
     */
    public void setRecipe(String recipe) {
        this.recipe = recipe == null ? null : recipe.trim();
    }
    
    

	public String getIsSoldOut() {
		return isSoldOut;
	}

	public void setIsSoldOut(String isSoldOut) {
		this.isSoldOut = isSoldOut;
	}
	

	public String getIsDetailedDescription() {
		return isDetailedDescription;
	}

	public void setIsDetailedDescription(String isDetailedDescription) {
		this.isDetailedDescription = isDetailedDescription;
	}
	
	

	public String getIsDetailedType() {
		return isDetailedType;
	}

	public void setIsDetailedType(String isDetailedType) {
		this.isDetailedType = isDetailedType;
	}

	public String getIsDetailedContents() {
		return isDetailedContents;
	}

	public void setIsDetailedContents(String isDetailedContents) {
		this.isDetailedContents = isDetailedContents;
	}

	public String getSalesTimeBegin() {
		return salesTimeBegin;
	}

	public void setSalesTimeBegin(String salesTimeBegin) {
		this.salesTimeBegin = salesTimeBegin;
	}

	public String getSalesTimeEnd() {
		return salesTimeEnd;
	}

	public void setSalesTimeEnd(String salesTimeEnd) {
		this.salesTimeEnd = salesTimeEnd;
	}

	@Override
	public String toString() {
		return "SvcItem [id=" + id + ", catId=" + catId + ", brandId=" + brandId + ", storeId=" + storeId + ", status="
				+ status + ", itemTp=" + itemTp + ", itemCd=" + itemCd + ", barcode=" + barcode + ", name=" + name
				+ ", shortName=" + shortName + ", price=" + price + ", supplyPrice=" + supplyPrice + ", purchasePrice="
				+ purchasePrice + ", tax=" + tax + ", discountPrice=" + discountPrice + ", serviceCharge="
				+ serviceCharge + ", isTaxIncluded=" + isTaxIncluded + ", taxTp=" + taxTp + ", isTipIncluded="
				+ isTipIncluded + ", isReward=" + isReward + ", isDiscountable=" + isDiscountable + ", isOptUsed="
				+ isOptUsed + ", isPackable=" + isPackable + ", isStamp=" + isStamp + ", mbIconTp=" + mbIconTp
				+ ", salesBegin=" + salesBegin + ", salesEnd=" + salesEnd + ", printerNo=" + printerNo + ", adminId="
				+ adminId + ", created=" + created + ", updated=" + updated + ", intro=" + intro + ", isStockUse="
				+ isStockUse + ", safeStockCnt=" + safeStockCnt + ", recipe=" + recipe + ", isSoldOut=" + isSoldOut
				+ ", isDetailedDescription=" + isDetailedDescription + ", isDetailedType=" + isDetailedType
				+ ", isDetailedContents=" + isDetailedContents + ", salesTimeBegin=" + salesTimeBegin
				+ ", salesTimeEnd=" + salesTimeEnd + "]";
	}


	   
    
}