package com.jc.pico.bean;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.Date;

@JsonIgnoreProperties(ignoreUnknown = true)
public class SvcSalesGoal {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_svc_sales_goal.ID
     *
     * @mbggenerated Tue Nov 29 13:56:07 KST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_svc_sales_goal.BRAND_ID
     *
     * @mbggenerated Tue Nov 29 13:56:07 KST 2016
     */
    private Long brandId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_svc_sales_goal.STORE_ID
     *
     * @mbggenerated Tue Nov 29 13:56:07 KST 2016
     */
    private Long storeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_svc_sales_goal.YEAR
     *
     * @mbggenerated Tue Nov 29 13:56:07 KST 2016
     */
    private String year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_svc_sales_goal.MONTH1_GOAL_AMT
     *
     * @mbggenerated Tue Nov 29 13:56:07 KST 2016
     */
    private Double month1GoalAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_svc_sales_goal.MONTH2_GOAL_AMT
     *
     * @mbggenerated Tue Nov 29 13:56:07 KST 2016
     */
    private Double month2GoalAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_svc_sales_goal.MONTH3_GOAL_AMT
     *
     * @mbggenerated Tue Nov 29 13:56:07 KST 2016
     */
    private Double month3GoalAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_svc_sales_goal.MONTH4_GOAL_AMT
     *
     * @mbggenerated Tue Nov 29 13:56:07 KST 2016
     */
    private Double month4GoalAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_svc_sales_goal.MONTH5_GOAL_AMT
     *
     * @mbggenerated Tue Nov 29 13:56:07 KST 2016
     */
    private Double month5GoalAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_svc_sales_goal.MONTH6_GOAL_AMT
     *
     * @mbggenerated Tue Nov 29 13:56:07 KST 2016
     */
    private Double month6GoalAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_svc_sales_goal.MONTH7_GOAL_AMT
     *
     * @mbggenerated Tue Nov 29 13:56:07 KST 2016
     */
    private Double month7GoalAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_svc_sales_goal.MONTH8_GOAL_AMT
     *
     * @mbggenerated Tue Nov 29 13:56:07 KST 2016
     */
    private Double month8GoalAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_svc_sales_goal.MONTH9_GOAL_AMT
     *
     * @mbggenerated Tue Nov 29 13:56:07 KST 2016
     */
    private Double month9GoalAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_svc_sales_goal.MONTH10_GOAL_AMT
     *
     * @mbggenerated Tue Nov 29 13:56:07 KST 2016
     */
    private Double month10GoalAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_svc_sales_goal.MONTH11_GOAL_AMT
     *
     * @mbggenerated Tue Nov 29 13:56:07 KST 2016
     */
    private Double month11GoalAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_svc_sales_goal.MONTH12_GOAL_AMT
     *
     * @mbggenerated Tue Nov 29 13:56:07 KST 2016
     */
    private Double month12GoalAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_svc_sales_goal.CREATED
     *
     * @mbggenerated Tue Nov 29 13:56:07 KST 2016
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_svc_sales_goal.UPDATED
     *
     * @mbggenerated Tue Nov 29 13:56:07 KST 2016
     */
    private Date updated;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_svc_sales_goal.ID
     *
     * @return the value of tb_svc_sales_goal.ID
     *
     * @mbggenerated Tue Nov 29 13:56:07 KST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_svc_sales_goal.ID
     *
     * @param id the value for tb_svc_sales_goal.ID
     *
     * @mbggenerated Tue Nov 29 13:56:07 KST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_svc_sales_goal.BRAND_ID
     *
     * @return the value of tb_svc_sales_goal.BRAND_ID
     *
     * @mbggenerated Tue Nov 29 13:56:07 KST 2016
     */
    public Long getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_svc_sales_goal.BRAND_ID
     *
     * @param brandId the value for tb_svc_sales_goal.BRAND_ID
     *
     * @mbggenerated Tue Nov 29 13:56:07 KST 2016
     */
    public void setBrandId(Long brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_svc_sales_goal.STORE_ID
     *
     * @return the value of tb_svc_sales_goal.STORE_ID
     *
     * @mbggenerated Tue Nov 29 13:56:07 KST 2016
     */
    public Long getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_svc_sales_goal.STORE_ID
     *
     * @param storeId the value for tb_svc_sales_goal.STORE_ID
     *
     * @mbggenerated Tue Nov 29 13:56:07 KST 2016
     */
    public void setStoreId(Long storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_svc_sales_goal.YEAR
     *
     * @return the value of tb_svc_sales_goal.YEAR
     *
     * @mbggenerated Tue Nov 29 13:56:07 KST 2016
     */
    public String getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_svc_sales_goal.YEAR
     *
     * @param year the value for tb_svc_sales_goal.YEAR
     *
     * @mbggenerated Tue Nov 29 13:56:07 KST 2016
     */
    public void setYear(String year) {
        this.year = year == null ? null : year.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_svc_sales_goal.MONTH1_GOAL_AMT
     *
     * @return the value of tb_svc_sales_goal.MONTH1_GOAL_AMT
     *
     * @mbggenerated Tue Nov 29 13:56:07 KST 2016
     */
    public Double getMonth1GoalAmt() {
        return month1GoalAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_svc_sales_goal.MONTH1_GOAL_AMT
     *
     * @param month1GoalAmt the value for tb_svc_sales_goal.MONTH1_GOAL_AMT
     *
     * @mbggenerated Tue Nov 29 13:56:07 KST 2016
     */
    public void setMonth1GoalAmt(Double month1GoalAmt) {
        this.month1GoalAmt = month1GoalAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_svc_sales_goal.MONTH2_GOAL_AMT
     *
     * @return the value of tb_svc_sales_goal.MONTH2_GOAL_AMT
     *
     * @mbggenerated Tue Nov 29 13:56:07 KST 2016
     */
    public Double getMonth2GoalAmt() {
        return month2GoalAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_svc_sales_goal.MONTH2_GOAL_AMT
     *
     * @param month2GoalAmt the value for tb_svc_sales_goal.MONTH2_GOAL_AMT
     *
     * @mbggenerated Tue Nov 29 13:56:07 KST 2016
     */
    public void setMonth2GoalAmt(Double month2GoalAmt) {
        this.month2GoalAmt = month2GoalAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_svc_sales_goal.MONTH3_GOAL_AMT
     *
     * @return the value of tb_svc_sales_goal.MONTH3_GOAL_AMT
     *
     * @mbggenerated Tue Nov 29 13:56:07 KST 2016
     */
    public Double getMonth3GoalAmt() {
        return month3GoalAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_svc_sales_goal.MONTH3_GOAL_AMT
     *
     * @param month3GoalAmt the value for tb_svc_sales_goal.MONTH3_GOAL_AMT
     *
     * @mbggenerated Tue Nov 29 13:56:07 KST 2016
     */
    public void setMonth3GoalAmt(Double month3GoalAmt) {
        this.month3GoalAmt = month3GoalAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_svc_sales_goal.MONTH4_GOAL_AMT
     *
     * @return the value of tb_svc_sales_goal.MONTH4_GOAL_AMT
     *
     * @mbggenerated Tue Nov 29 13:56:07 KST 2016
     */
    public Double getMonth4GoalAmt() {
        return month4GoalAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_svc_sales_goal.MONTH4_GOAL_AMT
     *
     * @param month4GoalAmt the value for tb_svc_sales_goal.MONTH4_GOAL_AMT
     *
     * @mbggenerated Tue Nov 29 13:56:07 KST 2016
     */
    public void setMonth4GoalAmt(Double month4GoalAmt) {
        this.month4GoalAmt = month4GoalAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_svc_sales_goal.MONTH5_GOAL_AMT
     *
     * @return the value of tb_svc_sales_goal.MONTH5_GOAL_AMT
     *
     * @mbggenerated Tue Nov 29 13:56:07 KST 2016
     */
    public Double getMonth5GoalAmt() {
        return month5GoalAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_svc_sales_goal.MONTH5_GOAL_AMT
     *
     * @param month5GoalAmt the value for tb_svc_sales_goal.MONTH5_GOAL_AMT
     *
     * @mbggenerated Tue Nov 29 13:56:07 KST 2016
     */
    public void setMonth5GoalAmt(Double month5GoalAmt) {
        this.month5GoalAmt = month5GoalAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_svc_sales_goal.MONTH6_GOAL_AMT
     *
     * @return the value of tb_svc_sales_goal.MONTH6_GOAL_AMT
     *
     * @mbggenerated Tue Nov 29 13:56:07 KST 2016
     */
    public Double getMonth6GoalAmt() {
        return month6GoalAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_svc_sales_goal.MONTH6_GOAL_AMT
     *
     * @param month6GoalAmt the value for tb_svc_sales_goal.MONTH6_GOAL_AMT
     *
     * @mbggenerated Tue Nov 29 13:56:07 KST 2016
     */
    public void setMonth6GoalAmt(Double month6GoalAmt) {
        this.month6GoalAmt = month6GoalAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_svc_sales_goal.MONTH7_GOAL_AMT
     *
     * @return the value of tb_svc_sales_goal.MONTH7_GOAL_AMT
     *
     * @mbggenerated Tue Nov 29 13:56:07 KST 2016
     */
    public Double getMonth7GoalAmt() {
        return month7GoalAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_svc_sales_goal.MONTH7_GOAL_AMT
     *
     * @param month7GoalAmt the value for tb_svc_sales_goal.MONTH7_GOAL_AMT
     *
     * @mbggenerated Tue Nov 29 13:56:07 KST 2016
     */
    public void setMonth7GoalAmt(Double month7GoalAmt) {
        this.month7GoalAmt = month7GoalAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_svc_sales_goal.MONTH8_GOAL_AMT
     *
     * @return the value of tb_svc_sales_goal.MONTH8_GOAL_AMT
     *
     * @mbggenerated Tue Nov 29 13:56:07 KST 2016
     */
    public Double getMonth8GoalAmt() {
        return month8GoalAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_svc_sales_goal.MONTH8_GOAL_AMT
     *
     * @param month8GoalAmt the value for tb_svc_sales_goal.MONTH8_GOAL_AMT
     *
     * @mbggenerated Tue Nov 29 13:56:07 KST 2016
     */
    public void setMonth8GoalAmt(Double month8GoalAmt) {
        this.month8GoalAmt = month8GoalAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_svc_sales_goal.MONTH9_GOAL_AMT
     *
     * @return the value of tb_svc_sales_goal.MONTH9_GOAL_AMT
     *
     * @mbggenerated Tue Nov 29 13:56:07 KST 2016
     */
    public Double getMonth9GoalAmt() {
        return month9GoalAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_svc_sales_goal.MONTH9_GOAL_AMT
     *
     * @param month9GoalAmt the value for tb_svc_sales_goal.MONTH9_GOAL_AMT
     *
     * @mbggenerated Tue Nov 29 13:56:07 KST 2016
     */
    public void setMonth9GoalAmt(Double month9GoalAmt) {
        this.month9GoalAmt = month9GoalAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_svc_sales_goal.MONTH10_GOAL_AMT
     *
     * @return the value of tb_svc_sales_goal.MONTH10_GOAL_AMT
     *
     * @mbggenerated Tue Nov 29 13:56:07 KST 2016
     */
    public Double getMonth10GoalAmt() {
        return month10GoalAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_svc_sales_goal.MONTH10_GOAL_AMT
     *
     * @param month10GoalAmt the value for tb_svc_sales_goal.MONTH10_GOAL_AMT
     *
     * @mbggenerated Tue Nov 29 13:56:07 KST 2016
     */
    public void setMonth10GoalAmt(Double month10GoalAmt) {
        this.month10GoalAmt = month10GoalAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_svc_sales_goal.MONTH11_GOAL_AMT
     *
     * @return the value of tb_svc_sales_goal.MONTH11_GOAL_AMT
     *
     * @mbggenerated Tue Nov 29 13:56:07 KST 2016
     */
    public Double getMonth11GoalAmt() {
        return month11GoalAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_svc_sales_goal.MONTH11_GOAL_AMT
     *
     * @param month11GoalAmt the value for tb_svc_sales_goal.MONTH11_GOAL_AMT
     *
     * @mbggenerated Tue Nov 29 13:56:07 KST 2016
     */
    public void setMonth11GoalAmt(Double month11GoalAmt) {
        this.month11GoalAmt = month11GoalAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_svc_sales_goal.MONTH12_GOAL_AMT
     *
     * @return the value of tb_svc_sales_goal.MONTH12_GOAL_AMT
     *
     * @mbggenerated Tue Nov 29 13:56:07 KST 2016
     */
    public Double getMonth12GoalAmt() {
        return month12GoalAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_svc_sales_goal.MONTH12_GOAL_AMT
     *
     * @param month12GoalAmt the value for tb_svc_sales_goal.MONTH12_GOAL_AMT
     *
     * @mbggenerated Tue Nov 29 13:56:07 KST 2016
     */
    public void setMonth12GoalAmt(Double month12GoalAmt) {
        this.month12GoalAmt = month12GoalAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_svc_sales_goal.CREATED
     *
     * @return the value of tb_svc_sales_goal.CREATED
     *
     * @mbggenerated Tue Nov 29 13:56:07 KST 2016
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_svc_sales_goal.CREATED
     *
     * @param created the value for tb_svc_sales_goal.CREATED
     *
     * @mbggenerated Tue Nov 29 13:56:07 KST 2016
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_svc_sales_goal.UPDATED
     *
     * @return the value of tb_svc_sales_goal.UPDATED
     *
     * @mbggenerated Tue Nov 29 13:56:07 KST 2016
     */
    public Date getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_svc_sales_goal.UPDATED
     *
     * @param updated the value for tb_svc_sales_goal.UPDATED
     *
     * @mbggenerated Tue Nov 29 13:56:07 KST 2016
     */
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
}