package com.jc.pico.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SvcStoreExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_svc_store
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_svc_store
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_svc_store
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_store
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    public SvcStoreExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_store
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_store
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_store
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_store
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_store
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_store
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_store
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_store
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_store
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_store
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_svc_store
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andServiceIdIsNull() {
            addCriterion("SERVICE_ID is null");
            return (Criteria) this;
        }

        public Criteria andServiceIdIsNotNull() {
            addCriterion("SERVICE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andServiceIdEqualTo(Long value) {
            addCriterion("SERVICE_ID =", value, "serviceId");
            return (Criteria) this;
        }

        public Criteria andServiceIdNotEqualTo(Long value) {
            addCriterion("SERVICE_ID <>", value, "serviceId");
            return (Criteria) this;
        }

        public Criteria andServiceIdGreaterThan(Long value) {
            addCriterion("SERVICE_ID >", value, "serviceId");
            return (Criteria) this;
        }

        public Criteria andServiceIdGreaterThanOrEqualTo(Long value) {
            addCriterion("SERVICE_ID >=", value, "serviceId");
            return (Criteria) this;
        }

        public Criteria andServiceIdLessThan(Long value) {
            addCriterion("SERVICE_ID <", value, "serviceId");
            return (Criteria) this;
        }

        public Criteria andServiceIdLessThanOrEqualTo(Long value) {
            addCriterion("SERVICE_ID <=", value, "serviceId");
            return (Criteria) this;
        }

        public Criteria andServiceIdIn(List<Long> values) {
            addCriterion("SERVICE_ID in", values, "serviceId");
            return (Criteria) this;
        }

        public Criteria andServiceIdNotIn(List<Long> values) {
            addCriterion("SERVICE_ID not in", values, "serviceId");
            return (Criteria) this;
        }

        public Criteria andServiceIdBetween(Long value1, Long value2) {
            addCriterion("SERVICE_ID between", value1, value2, "serviceId");
            return (Criteria) this;
        }

        public Criteria andServiceIdNotBetween(Long value1, Long value2) {
            addCriterion("SERVICE_ID not between", value1, value2, "serviceId");
            return (Criteria) this;
        }

        public Criteria andTenantIdIsNull() {
            addCriterion("TENANT_ID is null");
            return (Criteria) this;
        }

        public Criteria andTenantIdIsNotNull() {
            addCriterion("TENANT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andTenantIdEqualTo(Long value) {
            addCriterion("TENANT_ID =", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdNotEqualTo(Long value) {
            addCriterion("TENANT_ID <>", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdGreaterThan(Long value) {
            addCriterion("TENANT_ID >", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdGreaterThanOrEqualTo(Long value) {
            addCriterion("TENANT_ID >=", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdLessThan(Long value) {
            addCriterion("TENANT_ID <", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdLessThanOrEqualTo(Long value) {
            addCriterion("TENANT_ID <=", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdIn(List<Long> values) {
            addCriterion("TENANT_ID in", values, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdNotIn(List<Long> values) {
            addCriterion("TENANT_ID not in", values, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdBetween(Long value1, Long value2) {
            addCriterion("TENANT_ID between", value1, value2, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdNotBetween(Long value1, Long value2) {
            addCriterion("TENANT_ID not between", value1, value2, "tenantId");
            return (Criteria) this;
        }

        public Criteria andBrandIdIsNull() {
            addCriterion("BRAND_ID is null");
            return (Criteria) this;
        }

        public Criteria andBrandIdIsNotNull() {
            addCriterion("BRAND_ID is not null");
            return (Criteria) this;
        }

        public Criteria andBrandIdEqualTo(Long value) {
            addCriterion("BRAND_ID =", value, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdNotEqualTo(Long value) {
            addCriterion("BRAND_ID <>", value, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdGreaterThan(Long value) {
            addCriterion("BRAND_ID >", value, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdGreaterThanOrEqualTo(Long value) {
            addCriterion("BRAND_ID >=", value, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdLessThan(Long value) {
            addCriterion("BRAND_ID <", value, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdLessThanOrEqualTo(Long value) {
            addCriterion("BRAND_ID <=", value, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdIn(List<Long> values) {
            addCriterion("BRAND_ID in", values, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdNotIn(List<Long> values) {
            addCriterion("BRAND_ID not in", values, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdBetween(Long value1, Long value2) {
            addCriterion("BRAND_ID between", value1, value2, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdNotBetween(Long value1, Long value2) {
            addCriterion("BRAND_ID not between", value1, value2, "brandId");
            return (Criteria) this;
        }

        public Criteria andStoreCdIsNull() {
            addCriterion("STORE_CD is null");
            return (Criteria) this;
        }

        public Criteria andStoreCdIsNotNull() {
            addCriterion("STORE_CD is not null");
            return (Criteria) this;
        }

        public Criteria andStoreCdEqualTo(String value) {
            addCriterion("STORE_CD =", value, "storeCd");
            return (Criteria) this;
        }

        public Criteria andStoreCdNotEqualTo(String value) {
            addCriterion("STORE_CD <>", value, "storeCd");
            return (Criteria) this;
        }

        public Criteria andStoreCdGreaterThan(String value) {
            addCriterion("STORE_CD >", value, "storeCd");
            return (Criteria) this;
        }

        public Criteria andStoreCdGreaterThanOrEqualTo(String value) {
            addCriterion("STORE_CD >=", value, "storeCd");
            return (Criteria) this;
        }

        public Criteria andStoreCdLessThan(String value) {
            addCriterion("STORE_CD <", value, "storeCd");
            return (Criteria) this;
        }

        public Criteria andStoreCdLessThanOrEqualTo(String value) {
            addCriterion("STORE_CD <=", value, "storeCd");
            return (Criteria) this;
        }

        public Criteria andStoreCdLike(String value) {
            addCriterion("STORE_CD like", value, "storeCd");
            return (Criteria) this;
        }

        public Criteria andStoreCdNotLike(String value) {
            addCriterion("STORE_CD not like", value, "storeCd");
            return (Criteria) this;
        }

        public Criteria andStoreCdIn(List<String> values) {
            addCriterion("STORE_CD in", values, "storeCd");
            return (Criteria) this;
        }

        public Criteria andStoreCdNotIn(List<String> values) {
            addCriterion("STORE_CD not in", values, "storeCd");
            return (Criteria) this;
        }

        public Criteria andStoreCdBetween(String value1, String value2) {
            addCriterion("STORE_CD between", value1, value2, "storeCd");
            return (Criteria) this;
        }

        public Criteria andStoreCdNotBetween(String value1, String value2) {
            addCriterion("STORE_CD not between", value1, value2, "storeCd");
            return (Criteria) this;
        }

        public Criteria andSvcStIsNull() {
            addCriterion("SVC_ST is null");
            return (Criteria) this;
        }

        public Criteria andSvcStIsNotNull() {
            addCriterion("SVC_ST is not null");
            return (Criteria) this;
        }

        public Criteria andSvcStEqualTo(String value) {
            addCriterion("SVC_ST =", value, "svcSt");
            return (Criteria) this;
        }

        public Criteria andSvcStNotEqualTo(String value) {
            addCriterion("SVC_ST <>", value, "svcSt");
            return (Criteria) this;
        }

        public Criteria andSvcStGreaterThan(String value) {
            addCriterion("SVC_ST >", value, "svcSt");
            return (Criteria) this;
        }

        public Criteria andSvcStGreaterThanOrEqualTo(String value) {
            addCriterion("SVC_ST >=", value, "svcSt");
            return (Criteria) this;
        }

        public Criteria andSvcStLessThan(String value) {
            addCriterion("SVC_ST <", value, "svcSt");
            return (Criteria) this;
        }

        public Criteria andSvcStLessThanOrEqualTo(String value) {
            addCriterion("SVC_ST <=", value, "svcSt");
            return (Criteria) this;
        }

        public Criteria andSvcStLike(String value) {
            addCriterion("SVC_ST like", value, "svcSt");
            return (Criteria) this;
        }

        public Criteria andSvcStNotLike(String value) {
            addCriterion("SVC_ST not like", value, "svcSt");
            return (Criteria) this;
        }

        public Criteria andSvcStIn(List<String> values) {
            addCriterion("SVC_ST in", values, "svcSt");
            return (Criteria) this;
        }

        public Criteria andSvcStNotIn(List<String> values) {
            addCriterion("SVC_ST not in", values, "svcSt");
            return (Criteria) this;
        }

        public Criteria andSvcStBetween(String value1, String value2) {
            addCriterion("SVC_ST between", value1, value2, "svcSt");
            return (Criteria) this;
        }

        public Criteria andSvcStNotBetween(String value1, String value2) {
            addCriterion("SVC_ST not between", value1, value2, "svcSt");
            return (Criteria) this;
        }

        public Criteria andStoreStIsNull() {
            addCriterion("STORE_ST is null");
            return (Criteria) this;
        }

        public Criteria andStoreStIsNotNull() {
            addCriterion("STORE_ST is not null");
            return (Criteria) this;
        }

        public Criteria andStoreStEqualTo(String value) {
            addCriterion("STORE_ST =", value, "storeSt");
            return (Criteria) this;
        }

        public Criteria andStoreStNotEqualTo(String value) {
            addCriterion("STORE_ST <>", value, "storeSt");
            return (Criteria) this;
        }

        public Criteria andStoreStGreaterThan(String value) {
            addCriterion("STORE_ST >", value, "storeSt");
            return (Criteria) this;
        }

        public Criteria andStoreStGreaterThanOrEqualTo(String value) {
            addCriterion("STORE_ST >=", value, "storeSt");
            return (Criteria) this;
        }

        public Criteria andStoreStLessThan(String value) {
            addCriterion("STORE_ST <", value, "storeSt");
            return (Criteria) this;
        }

        public Criteria andStoreStLessThanOrEqualTo(String value) {
            addCriterion("STORE_ST <=", value, "storeSt");
            return (Criteria) this;
        }

        public Criteria andStoreStLike(String value) {
            addCriterion("STORE_ST like", value, "storeSt");
            return (Criteria) this;
        }

        public Criteria andStoreStNotLike(String value) {
            addCriterion("STORE_ST not like", value, "storeSt");
            return (Criteria) this;
        }

        public Criteria andStoreStIn(List<String> values) {
            addCriterion("STORE_ST in", values, "storeSt");
            return (Criteria) this;
        }

        public Criteria andStoreStNotIn(List<String> values) {
            addCriterion("STORE_ST not in", values, "storeSt");
            return (Criteria) this;
        }

        public Criteria andStoreStBetween(String value1, String value2) {
            addCriterion("STORE_ST between", value1, value2, "storeSt");
            return (Criteria) this;
        }

        public Criteria andStoreStNotBetween(String value1, String value2) {
            addCriterion("STORE_ST not between", value1, value2, "storeSt");
            return (Criteria) this;
        }

        public Criteria andStoreTpIsNull() {
            addCriterion("STORE_TP is null");
            return (Criteria) this;
        }

        public Criteria andStoreTpIsNotNull() {
            addCriterion("STORE_TP is not null");
            return (Criteria) this;
        }

        public Criteria andStoreTpEqualTo(String value) {
            addCriterion("STORE_TP =", value, "storeTp");
            return (Criteria) this;
        }

        public Criteria andStoreTpNotEqualTo(String value) {
            addCriterion("STORE_TP <>", value, "storeTp");
            return (Criteria) this;
        }

        public Criteria andStoreTpGreaterThan(String value) {
            addCriterion("STORE_TP >", value, "storeTp");
            return (Criteria) this;
        }

        public Criteria andStoreTpGreaterThanOrEqualTo(String value) {
            addCriterion("STORE_TP >=", value, "storeTp");
            return (Criteria) this;
        }

        public Criteria andStoreTpLessThan(String value) {
            addCriterion("STORE_TP <", value, "storeTp");
            return (Criteria) this;
        }

        public Criteria andStoreTpLessThanOrEqualTo(String value) {
            addCriterion("STORE_TP <=", value, "storeTp");
            return (Criteria) this;
        }

        public Criteria andStoreTpLike(String value) {
            addCriterion("STORE_TP like", value, "storeTp");
            return (Criteria) this;
        }

        public Criteria andStoreTpNotLike(String value) {
            addCriterion("STORE_TP not like", value, "storeTp");
            return (Criteria) this;
        }

        public Criteria andStoreTpIn(List<String> values) {
            addCriterion("STORE_TP in", values, "storeTp");
            return (Criteria) this;
        }

        public Criteria andStoreTpNotIn(List<String> values) {
            addCriterion("STORE_TP not in", values, "storeTp");
            return (Criteria) this;
        }

        public Criteria andStoreTpBetween(String value1, String value2) {
            addCriterion("STORE_TP between", value1, value2, "storeTp");
            return (Criteria) this;
        }

        public Criteria andStoreTpNotBetween(String value1, String value2) {
            addCriterion("STORE_TP not between", value1, value2, "storeTp");
            return (Criteria) this;
        }

        public Criteria andBizNoIsNull() {
            addCriterion("BIZ_NO is null");
            return (Criteria) this;
        }

        public Criteria andBizNoIsNotNull() {
            addCriterion("BIZ_NO is not null");
            return (Criteria) this;
        }

        public Criteria andBizNoEqualTo(String value) {
            addCriterion("BIZ_NO =", value, "bizNo");
            return (Criteria) this;
        }

        public Criteria andBizNoNotEqualTo(String value) {
            addCriterion("BIZ_NO <>", value, "bizNo");
            return (Criteria) this;
        }

        public Criteria andBizNoGreaterThan(String value) {
            addCriterion("BIZ_NO >", value, "bizNo");
            return (Criteria) this;
        }

        public Criteria andBizNoGreaterThanOrEqualTo(String value) {
            addCriterion("BIZ_NO >=", value, "bizNo");
            return (Criteria) this;
        }

        public Criteria andBizNoLessThan(String value) {
            addCriterion("BIZ_NO <", value, "bizNo");
            return (Criteria) this;
        }

        public Criteria andBizNoLessThanOrEqualTo(String value) {
            addCriterion("BIZ_NO <=", value, "bizNo");
            return (Criteria) this;
        }

        public Criteria andBizNoLike(String value) {
            addCriterion("BIZ_NO like", value, "bizNo");
            return (Criteria) this;
        }

        public Criteria andBizNoNotLike(String value) {
            addCriterion("BIZ_NO not like", value, "bizNo");
            return (Criteria) this;
        }

        public Criteria andBizNoIn(List<String> values) {
            addCriterion("BIZ_NO in", values, "bizNo");
            return (Criteria) this;
        }

        public Criteria andBizNoNotIn(List<String> values) {
            addCriterion("BIZ_NO not in", values, "bizNo");
            return (Criteria) this;
        }

        public Criteria andBizNoBetween(String value1, String value2) {
            addCriterion("BIZ_NO between", value1, value2, "bizNo");
            return (Criteria) this;
        }

        public Criteria andBizNoNotBetween(String value1, String value2) {
            addCriterion("BIZ_NO not between", value1, value2, "bizNo");
            return (Criteria) this;
        }

        public Criteria andOwnerNmIsNull() {
            addCriterion("OWNER_NM is null");
            return (Criteria) this;
        }

        public Criteria andOwnerNmIsNotNull() {
            addCriterion("OWNER_NM is not null");
            return (Criteria) this;
        }

        public Criteria andOwnerNmEqualTo(String value) {
            addCriterion("OWNER_NM =", value, "ownerNm");
            return (Criteria) this;
        }

        public Criteria andOwnerNmNotEqualTo(String value) {
            addCriterion("OWNER_NM <>", value, "ownerNm");
            return (Criteria) this;
        }

        public Criteria andOwnerNmGreaterThan(String value) {
            addCriterion("OWNER_NM >", value, "ownerNm");
            return (Criteria) this;
        }

        public Criteria andOwnerNmGreaterThanOrEqualTo(String value) {
            addCriterion("OWNER_NM >=", value, "ownerNm");
            return (Criteria) this;
        }

        public Criteria andOwnerNmLessThan(String value) {
            addCriterion("OWNER_NM <", value, "ownerNm");
            return (Criteria) this;
        }

        public Criteria andOwnerNmLessThanOrEqualTo(String value) {
            addCriterion("OWNER_NM <=", value, "ownerNm");
            return (Criteria) this;
        }

        public Criteria andOwnerNmLike(String value) {
            addCriterion("OWNER_NM like", value, "ownerNm");
            return (Criteria) this;
        }

        public Criteria andOwnerNmNotLike(String value) {
            addCriterion("OWNER_NM not like", value, "ownerNm");
            return (Criteria) this;
        }

        public Criteria andOwnerNmIn(List<String> values) {
            addCriterion("OWNER_NM in", values, "ownerNm");
            return (Criteria) this;
        }

        public Criteria andOwnerNmNotIn(List<String> values) {
            addCriterion("OWNER_NM not in", values, "ownerNm");
            return (Criteria) this;
        }

        public Criteria andOwnerNmBetween(String value1, String value2) {
            addCriterion("OWNER_NM between", value1, value2, "ownerNm");
            return (Criteria) this;
        }

        public Criteria andOwnerNmNotBetween(String value1, String value2) {
            addCriterion("OWNER_NM not between", value1, value2, "ownerNm");
            return (Criteria) this;
        }

        public Criteria andStoreNmIsNull() {
            addCriterion("STORE_NM is null");
            return (Criteria) this;
        }

        public Criteria andStoreNmIsNotNull() {
            addCriterion("STORE_NM is not null");
            return (Criteria) this;
        }

        public Criteria andStoreNmEqualTo(String value) {
            addCriterion("STORE_NM =", value, "storeNm");
            return (Criteria) this;
        }

        public Criteria andStoreNmNotEqualTo(String value) {
            addCriterion("STORE_NM <>", value, "storeNm");
            return (Criteria) this;
        }

        public Criteria andStoreNmGreaterThan(String value) {
            addCriterion("STORE_NM >", value, "storeNm");
            return (Criteria) this;
        }

        public Criteria andStoreNmGreaterThanOrEqualTo(String value) {
            addCriterion("STORE_NM >=", value, "storeNm");
            return (Criteria) this;
        }

        public Criteria andStoreNmLessThan(String value) {
            addCriterion("STORE_NM <", value, "storeNm");
            return (Criteria) this;
        }

        public Criteria andStoreNmLessThanOrEqualTo(String value) {
            addCriterion("STORE_NM <=", value, "storeNm");
            return (Criteria) this;
        }

        public Criteria andStoreNmLike(String value) {
            addCriterion("STORE_NM like", value, "storeNm");
            return (Criteria) this;
        }

        public Criteria andStoreNmNotLike(String value) {
            addCriterion("STORE_NM not like", value, "storeNm");
            return (Criteria) this;
        }

        public Criteria andStoreNmIn(List<String> values) {
            addCriterion("STORE_NM in", values, "storeNm");
            return (Criteria) this;
        }

        public Criteria andStoreNmNotIn(List<String> values) {
            addCriterion("STORE_NM not in", values, "storeNm");
            return (Criteria) this;
        }

        public Criteria andStoreNmBetween(String value1, String value2) {
            addCriterion("STORE_NM between", value1, value2, "storeNm");
            return (Criteria) this;
        }

        public Criteria andStoreNmNotBetween(String value1, String value2) {
            addCriterion("STORE_NM not between", value1, value2, "storeNm");
            return (Criteria) this;
        }

        public Criteria andBizCatIsNull() {
            addCriterion("BIZ_CAT is null");
            return (Criteria) this;
        }

        public Criteria andBizCatIsNotNull() {
            addCriterion("BIZ_CAT is not null");
            return (Criteria) this;
        }

        public Criteria andBizCatEqualTo(String value) {
            addCriterion("BIZ_CAT =", value, "bizCat");
            return (Criteria) this;
        }

        public Criteria andBizCatNotEqualTo(String value) {
            addCriterion("BIZ_CAT <>", value, "bizCat");
            return (Criteria) this;
        }

        public Criteria andBizCatGreaterThan(String value) {
            addCriterion("BIZ_CAT >", value, "bizCat");
            return (Criteria) this;
        }

        public Criteria andBizCatGreaterThanOrEqualTo(String value) {
            addCriterion("BIZ_CAT >=", value, "bizCat");
            return (Criteria) this;
        }

        public Criteria andBizCatLessThan(String value) {
            addCriterion("BIZ_CAT <", value, "bizCat");
            return (Criteria) this;
        }

        public Criteria andBizCatLessThanOrEqualTo(String value) {
            addCriterion("BIZ_CAT <=", value, "bizCat");
            return (Criteria) this;
        }

        public Criteria andBizCatLike(String value) {
            addCriterion("BIZ_CAT like", value, "bizCat");
            return (Criteria) this;
        }

        public Criteria andBizCatNotLike(String value) {
            addCriterion("BIZ_CAT not like", value, "bizCat");
            return (Criteria) this;
        }

        public Criteria andBizCatIn(List<String> values) {
            addCriterion("BIZ_CAT in", values, "bizCat");
            return (Criteria) this;
        }

        public Criteria andBizCatNotIn(List<String> values) {
            addCriterion("BIZ_CAT not in", values, "bizCat");
            return (Criteria) this;
        }

        public Criteria andBizCatBetween(String value1, String value2) {
            addCriterion("BIZ_CAT between", value1, value2, "bizCat");
            return (Criteria) this;
        }

        public Criteria andBizCatNotBetween(String value1, String value2) {
            addCriterion("BIZ_CAT not between", value1, value2, "bizCat");
            return (Criteria) this;
        }

        public Criteria andEmailIsNull() {
            addCriterion("EMAIL is null");
            return (Criteria) this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("EMAIL is not null");
            return (Criteria) this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("EMAIL =", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("EMAIL <>", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThan(String value) {
            addCriterion("EMAIL >", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("EMAIL >=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThan(String value) {
            addCriterion("EMAIL <", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("EMAIL <=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLike(String value) {
            addCriterion("EMAIL like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("EMAIL not like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailIn(List<String> values) {
            addCriterion("EMAIL in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotIn(List<String> values) {
            addCriterion("EMAIL not in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("EMAIL between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("EMAIL not between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andFaxCountryCdIsNull() {
            addCriterion("FAX_COUNTRY_CD is null");
            return (Criteria) this;
        }

        public Criteria andFaxCountryCdIsNotNull() {
            addCriterion("FAX_COUNTRY_CD is not null");
            return (Criteria) this;
        }

        public Criteria andFaxCountryCdEqualTo(String value) {
            addCriterion("FAX_COUNTRY_CD =", value, "faxCountryCd");
            return (Criteria) this;
        }

        public Criteria andFaxCountryCdNotEqualTo(String value) {
            addCriterion("FAX_COUNTRY_CD <>", value, "faxCountryCd");
            return (Criteria) this;
        }

        public Criteria andFaxCountryCdGreaterThan(String value) {
            addCriterion("FAX_COUNTRY_CD >", value, "faxCountryCd");
            return (Criteria) this;
        }

        public Criteria andFaxCountryCdGreaterThanOrEqualTo(String value) {
            addCriterion("FAX_COUNTRY_CD >=", value, "faxCountryCd");
            return (Criteria) this;
        }

        public Criteria andFaxCountryCdLessThan(String value) {
            addCriterion("FAX_COUNTRY_CD <", value, "faxCountryCd");
            return (Criteria) this;
        }

        public Criteria andFaxCountryCdLessThanOrEqualTo(String value) {
            addCriterion("FAX_COUNTRY_CD <=", value, "faxCountryCd");
            return (Criteria) this;
        }

        public Criteria andFaxCountryCdLike(String value) {
            addCriterion("FAX_COUNTRY_CD like", value, "faxCountryCd");
            return (Criteria) this;
        }

        public Criteria andFaxCountryCdNotLike(String value) {
            addCriterion("FAX_COUNTRY_CD not like", value, "faxCountryCd");
            return (Criteria) this;
        }

        public Criteria andFaxCountryCdIn(List<String> values) {
            addCriterion("FAX_COUNTRY_CD in", values, "faxCountryCd");
            return (Criteria) this;
        }

        public Criteria andFaxCountryCdNotIn(List<String> values) {
            addCriterion("FAX_COUNTRY_CD not in", values, "faxCountryCd");
            return (Criteria) this;
        }

        public Criteria andFaxCountryCdBetween(String value1, String value2) {
            addCriterion("FAX_COUNTRY_CD between", value1, value2, "faxCountryCd");
            return (Criteria) this;
        }

        public Criteria andFaxCountryCdNotBetween(String value1, String value2) {
            addCriterion("FAX_COUNTRY_CD not between", value1, value2, "faxCountryCd");
            return (Criteria) this;
        }

        public Criteria andFaxIsNull() {
            addCriterion("FAX is null");
            return (Criteria) this;
        }

        public Criteria andFaxIsNotNull() {
            addCriterion("FAX is not null");
            return (Criteria) this;
        }

        public Criteria andFaxEqualTo(String value) {
            addCriterion("FAX =", value, "fax");
            return (Criteria) this;
        }

        public Criteria andFaxNotEqualTo(String value) {
            addCriterion("FAX <>", value, "fax");
            return (Criteria) this;
        }

        public Criteria andFaxGreaterThan(String value) {
            addCriterion("FAX >", value, "fax");
            return (Criteria) this;
        }

        public Criteria andFaxGreaterThanOrEqualTo(String value) {
            addCriterion("FAX >=", value, "fax");
            return (Criteria) this;
        }

        public Criteria andFaxLessThan(String value) {
            addCriterion("FAX <", value, "fax");
            return (Criteria) this;
        }

        public Criteria andFaxLessThanOrEqualTo(String value) {
            addCriterion("FAX <=", value, "fax");
            return (Criteria) this;
        }

        public Criteria andFaxLike(String value) {
            addCriterion("FAX like", value, "fax");
            return (Criteria) this;
        }

        public Criteria andFaxNotLike(String value) {
            addCriterion("FAX not like", value, "fax");
            return (Criteria) this;
        }

        public Criteria andFaxIn(List<String> values) {
            addCriterion("FAX in", values, "fax");
            return (Criteria) this;
        }

        public Criteria andFaxNotIn(List<String> values) {
            addCriterion("FAX not in", values, "fax");
            return (Criteria) this;
        }

        public Criteria andFaxBetween(String value1, String value2) {
            addCriterion("FAX between", value1, value2, "fax");
            return (Criteria) this;
        }

        public Criteria andFaxNotBetween(String value1, String value2) {
            addCriterion("FAX not between", value1, value2, "fax");
            return (Criteria) this;
        }

        public Criteria andMbCountryCdIsNull() {
            addCriterion("MB_COUNTRY_CD is null");
            return (Criteria) this;
        }

        public Criteria andMbCountryCdIsNotNull() {
            addCriterion("MB_COUNTRY_CD is not null");
            return (Criteria) this;
        }

        public Criteria andMbCountryCdEqualTo(String value) {
            addCriterion("MB_COUNTRY_CD =", value, "mbCountryCd");
            return (Criteria) this;
        }

        public Criteria andMbCountryCdNotEqualTo(String value) {
            addCriterion("MB_COUNTRY_CD <>", value, "mbCountryCd");
            return (Criteria) this;
        }

        public Criteria andMbCountryCdGreaterThan(String value) {
            addCriterion("MB_COUNTRY_CD >", value, "mbCountryCd");
            return (Criteria) this;
        }

        public Criteria andMbCountryCdGreaterThanOrEqualTo(String value) {
            addCriterion("MB_COUNTRY_CD >=", value, "mbCountryCd");
            return (Criteria) this;
        }

        public Criteria andMbCountryCdLessThan(String value) {
            addCriterion("MB_COUNTRY_CD <", value, "mbCountryCd");
            return (Criteria) this;
        }

        public Criteria andMbCountryCdLessThanOrEqualTo(String value) {
            addCriterion("MB_COUNTRY_CD <=", value, "mbCountryCd");
            return (Criteria) this;
        }

        public Criteria andMbCountryCdLike(String value) {
            addCriterion("MB_COUNTRY_CD like", value, "mbCountryCd");
            return (Criteria) this;
        }

        public Criteria andMbCountryCdNotLike(String value) {
            addCriterion("MB_COUNTRY_CD not like", value, "mbCountryCd");
            return (Criteria) this;
        }

        public Criteria andMbCountryCdIn(List<String> values) {
            addCriterion("MB_COUNTRY_CD in", values, "mbCountryCd");
            return (Criteria) this;
        }

        public Criteria andMbCountryCdNotIn(List<String> values) {
            addCriterion("MB_COUNTRY_CD not in", values, "mbCountryCd");
            return (Criteria) this;
        }

        public Criteria andMbCountryCdBetween(String value1, String value2) {
            addCriterion("MB_COUNTRY_CD between", value1, value2, "mbCountryCd");
            return (Criteria) this;
        }

        public Criteria andMbCountryCdNotBetween(String value1, String value2) {
            addCriterion("MB_COUNTRY_CD not between", value1, value2, "mbCountryCd");
            return (Criteria) this;
        }

        public Criteria andMbIsNull() {
            addCriterion("MB is null");
            return (Criteria) this;
        }

        public Criteria andMbIsNotNull() {
            addCriterion("MB is not null");
            return (Criteria) this;
        }

        public Criteria andMbEqualTo(String value) {
            addCriterion("MB =", value, "mb");
            return (Criteria) this;
        }

        public Criteria andMbNotEqualTo(String value) {
            addCriterion("MB <>", value, "mb");
            return (Criteria) this;
        }

        public Criteria andMbGreaterThan(String value) {
            addCriterion("MB >", value, "mb");
            return (Criteria) this;
        }

        public Criteria andMbGreaterThanOrEqualTo(String value) {
            addCriterion("MB >=", value, "mb");
            return (Criteria) this;
        }

        public Criteria andMbLessThan(String value) {
            addCriterion("MB <", value, "mb");
            return (Criteria) this;
        }

        public Criteria andMbLessThanOrEqualTo(String value) {
            addCriterion("MB <=", value, "mb");
            return (Criteria) this;
        }

        public Criteria andMbLike(String value) {
            addCriterion("MB like", value, "mb");
            return (Criteria) this;
        }

        public Criteria andMbNotLike(String value) {
            addCriterion("MB not like", value, "mb");
            return (Criteria) this;
        }

        public Criteria andMbIn(List<String> values) {
            addCriterion("MB in", values, "mb");
            return (Criteria) this;
        }

        public Criteria andMbNotIn(List<String> values) {
            addCriterion("MB not in", values, "mb");
            return (Criteria) this;
        }

        public Criteria andMbBetween(String value1, String value2) {
            addCriterion("MB between", value1, value2, "mb");
            return (Criteria) this;
        }

        public Criteria andMbNotBetween(String value1, String value2) {
            addCriterion("MB not between", value1, value2, "mb");
            return (Criteria) this;
        }

        public Criteria andTelCountryCdIsNull() {
            addCriterion("TEL_COUNTRY_CD is null");
            return (Criteria) this;
        }

        public Criteria andTelCountryCdIsNotNull() {
            addCriterion("TEL_COUNTRY_CD is not null");
            return (Criteria) this;
        }

        public Criteria andTelCountryCdEqualTo(String value) {
            addCriterion("TEL_COUNTRY_CD =", value, "telCountryCd");
            return (Criteria) this;
        }

        public Criteria andTelCountryCdNotEqualTo(String value) {
            addCriterion("TEL_COUNTRY_CD <>", value, "telCountryCd");
            return (Criteria) this;
        }

        public Criteria andTelCountryCdGreaterThan(String value) {
            addCriterion("TEL_COUNTRY_CD >", value, "telCountryCd");
            return (Criteria) this;
        }

        public Criteria andTelCountryCdGreaterThanOrEqualTo(String value) {
            addCriterion("TEL_COUNTRY_CD >=", value, "telCountryCd");
            return (Criteria) this;
        }

        public Criteria andTelCountryCdLessThan(String value) {
            addCriterion("TEL_COUNTRY_CD <", value, "telCountryCd");
            return (Criteria) this;
        }

        public Criteria andTelCountryCdLessThanOrEqualTo(String value) {
            addCriterion("TEL_COUNTRY_CD <=", value, "telCountryCd");
            return (Criteria) this;
        }

        public Criteria andTelCountryCdLike(String value) {
            addCriterion("TEL_COUNTRY_CD like", value, "telCountryCd");
            return (Criteria) this;
        }

        public Criteria andTelCountryCdNotLike(String value) {
            addCriterion("TEL_COUNTRY_CD not like", value, "telCountryCd");
            return (Criteria) this;
        }

        public Criteria andTelCountryCdIn(List<String> values) {
            addCriterion("TEL_COUNTRY_CD in", values, "telCountryCd");
            return (Criteria) this;
        }

        public Criteria andTelCountryCdNotIn(List<String> values) {
            addCriterion("TEL_COUNTRY_CD not in", values, "telCountryCd");
            return (Criteria) this;
        }

        public Criteria andTelCountryCdBetween(String value1, String value2) {
            addCriterion("TEL_COUNTRY_CD between", value1, value2, "telCountryCd");
            return (Criteria) this;
        }

        public Criteria andTelCountryCdNotBetween(String value1, String value2) {
            addCriterion("TEL_COUNTRY_CD not between", value1, value2, "telCountryCd");
            return (Criteria) this;
        }

        public Criteria andTelIsNull() {
            addCriterion("TEL is null");
            return (Criteria) this;
        }

        public Criteria andTelIsNotNull() {
            addCriterion("TEL is not null");
            return (Criteria) this;
        }

        public Criteria andTelEqualTo(String value) {
            addCriterion("TEL =", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelNotEqualTo(String value) {
            addCriterion("TEL <>", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelGreaterThan(String value) {
            addCriterion("TEL >", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelGreaterThanOrEqualTo(String value) {
            addCriterion("TEL >=", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelLessThan(String value) {
            addCriterion("TEL <", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelLessThanOrEqualTo(String value) {
            addCriterion("TEL <=", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelLike(String value) {
            addCriterion("TEL like", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelNotLike(String value) {
            addCriterion("TEL not like", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelIn(List<String> values) {
            addCriterion("TEL in", values, "tel");
            return (Criteria) this;
        }

        public Criteria andTelNotIn(List<String> values) {
            addCriterion("TEL not in", values, "tel");
            return (Criteria) this;
        }

        public Criteria andTelBetween(String value1, String value2) {
            addCriterion("TEL between", value1, value2, "tel");
            return (Criteria) this;
        }

        public Criteria andTelNotBetween(String value1, String value2) {
            addCriterion("TEL not between", value1, value2, "tel");
            return (Criteria) this;
        }

        public Criteria andCountryIsNull() {
            addCriterion("COUNTRY is null");
            return (Criteria) this;
        }

        public Criteria andCountryIsNotNull() {
            addCriterion("COUNTRY is not null");
            return (Criteria) this;
        }

        public Criteria andCountryEqualTo(String value) {
            addCriterion("COUNTRY =", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryNotEqualTo(String value) {
            addCriterion("COUNTRY <>", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryGreaterThan(String value) {
            addCriterion("COUNTRY >", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryGreaterThanOrEqualTo(String value) {
            addCriterion("COUNTRY >=", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryLessThan(String value) {
            addCriterion("COUNTRY <", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryLessThanOrEqualTo(String value) {
            addCriterion("COUNTRY <=", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryLike(String value) {
            addCriterion("COUNTRY like", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryNotLike(String value) {
            addCriterion("COUNTRY not like", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryIn(List<String> values) {
            addCriterion("COUNTRY in", values, "country");
            return (Criteria) this;
        }

        public Criteria andCountryNotIn(List<String> values) {
            addCriterion("COUNTRY not in", values, "country");
            return (Criteria) this;
        }

        public Criteria andCountryBetween(String value1, String value2) {
            addCriterion("COUNTRY between", value1, value2, "country");
            return (Criteria) this;
        }

        public Criteria andCountryNotBetween(String value1, String value2) {
            addCriterion("COUNTRY not between", value1, value2, "country");
            return (Criteria) this;
        }

        public Criteria andRegionIsNull() {
            addCriterion("REGION is null");
            return (Criteria) this;
        }

        public Criteria andRegionIsNotNull() {
            addCriterion("REGION is not null");
            return (Criteria) this;
        }

        public Criteria andRegionEqualTo(String value) {
            addCriterion("REGION =", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionNotEqualTo(String value) {
            addCriterion("REGION <>", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionGreaterThan(String value) {
            addCriterion("REGION >", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionGreaterThanOrEqualTo(String value) {
            addCriterion("REGION >=", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionLessThan(String value) {
            addCriterion("REGION <", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionLessThanOrEqualTo(String value) {
            addCriterion("REGION <=", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionLike(String value) {
            addCriterion("REGION like", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionNotLike(String value) {
            addCriterion("REGION not like", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionIn(List<String> values) {
            addCriterion("REGION in", values, "region");
            return (Criteria) this;
        }

        public Criteria andRegionNotIn(List<String> values) {
            addCriterion("REGION not in", values, "region");
            return (Criteria) this;
        }

        public Criteria andRegionBetween(String value1, String value2) {
            addCriterion("REGION between", value1, value2, "region");
            return (Criteria) this;
        }

        public Criteria andRegionNotBetween(String value1, String value2) {
            addCriterion("REGION not between", value1, value2, "region");
            return (Criteria) this;
        }

        public Criteria andCityIsNull() {
            addCriterion("CITY is null");
            return (Criteria) this;
        }

        public Criteria andCityIsNotNull() {
            addCriterion("CITY is not null");
            return (Criteria) this;
        }

        public Criteria andCityEqualTo(String value) {
            addCriterion("CITY =", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotEqualTo(String value) {
            addCriterion("CITY <>", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityGreaterThan(String value) {
            addCriterion("CITY >", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityGreaterThanOrEqualTo(String value) {
            addCriterion("CITY >=", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLessThan(String value) {
            addCriterion("CITY <", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLessThanOrEqualTo(String value) {
            addCriterion("CITY <=", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLike(String value) {
            addCriterion("CITY like", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotLike(String value) {
            addCriterion("CITY not like", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityIn(List<String> values) {
            addCriterion("CITY in", values, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotIn(List<String> values) {
            addCriterion("CITY not in", values, "city");
            return (Criteria) this;
        }

        public Criteria andCityBetween(String value1, String value2) {
            addCriterion("CITY between", value1, value2, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotBetween(String value1, String value2) {
            addCriterion("CITY not between", value1, value2, "city");
            return (Criteria) this;
        }

        public Criteria andAddr1IsNull() {
            addCriterion("ADDR1 is null");
            return (Criteria) this;
        }

        public Criteria andAddr1IsNotNull() {
            addCriterion("ADDR1 is not null");
            return (Criteria) this;
        }

        public Criteria andAddr1EqualTo(String value) {
            addCriterion("ADDR1 =", value, "addr1");
            return (Criteria) this;
        }

        public Criteria andAddr1NotEqualTo(String value) {
            addCriterion("ADDR1 <>", value, "addr1");
            return (Criteria) this;
        }

        public Criteria andAddr1GreaterThan(String value) {
            addCriterion("ADDR1 >", value, "addr1");
            return (Criteria) this;
        }

        public Criteria andAddr1GreaterThanOrEqualTo(String value) {
            addCriterion("ADDR1 >=", value, "addr1");
            return (Criteria) this;
        }

        public Criteria andAddr1LessThan(String value) {
            addCriterion("ADDR1 <", value, "addr1");
            return (Criteria) this;
        }

        public Criteria andAddr1LessThanOrEqualTo(String value) {
            addCriterion("ADDR1 <=", value, "addr1");
            return (Criteria) this;
        }

        public Criteria andAddr1Like(String value) {
            addCriterion("ADDR1 like", value, "addr1");
            return (Criteria) this;
        }

        public Criteria andAddr1NotLike(String value) {
            addCriterion("ADDR1 not like", value, "addr1");
            return (Criteria) this;
        }

        public Criteria andAddr1In(List<String> values) {
            addCriterion("ADDR1 in", values, "addr1");
            return (Criteria) this;
        }

        public Criteria andAddr1NotIn(List<String> values) {
            addCriterion("ADDR1 not in", values, "addr1");
            return (Criteria) this;
        }

        public Criteria andAddr1Between(String value1, String value2) {
            addCriterion("ADDR1 between", value1, value2, "addr1");
            return (Criteria) this;
        }

        public Criteria andAddr1NotBetween(String value1, String value2) {
            addCriterion("ADDR1 not between", value1, value2, "addr1");
            return (Criteria) this;
        }

        public Criteria andAddr2IsNull() {
            addCriterion("ADDR2 is null");
            return (Criteria) this;
        }

        public Criteria andAddr2IsNotNull() {
            addCriterion("ADDR2 is not null");
            return (Criteria) this;
        }

        public Criteria andAddr2EqualTo(String value) {
            addCriterion("ADDR2 =", value, "addr2");
            return (Criteria) this;
        }

        public Criteria andAddr2NotEqualTo(String value) {
            addCriterion("ADDR2 <>", value, "addr2");
            return (Criteria) this;
        }

        public Criteria andAddr2GreaterThan(String value) {
            addCriterion("ADDR2 >", value, "addr2");
            return (Criteria) this;
        }

        public Criteria andAddr2GreaterThanOrEqualTo(String value) {
            addCriterion("ADDR2 >=", value, "addr2");
            return (Criteria) this;
        }

        public Criteria andAddr2LessThan(String value) {
            addCriterion("ADDR2 <", value, "addr2");
            return (Criteria) this;
        }

        public Criteria andAddr2LessThanOrEqualTo(String value) {
            addCriterion("ADDR2 <=", value, "addr2");
            return (Criteria) this;
        }

        public Criteria andAddr2Like(String value) {
            addCriterion("ADDR2 like", value, "addr2");
            return (Criteria) this;
        }

        public Criteria andAddr2NotLike(String value) {
            addCriterion("ADDR2 not like", value, "addr2");
            return (Criteria) this;
        }

        public Criteria andAddr2In(List<String> values) {
            addCriterion("ADDR2 in", values, "addr2");
            return (Criteria) this;
        }

        public Criteria andAddr2NotIn(List<String> values) {
            addCriterion("ADDR2 not in", values, "addr2");
            return (Criteria) this;
        }

        public Criteria andAddr2Between(String value1, String value2) {
            addCriterion("ADDR2 between", value1, value2, "addr2");
            return (Criteria) this;
        }

        public Criteria andAddr2NotBetween(String value1, String value2) {
            addCriterion("ADDR2 not between", value1, value2, "addr2");
            return (Criteria) this;
        }

        public Criteria andZipIsNull() {
            addCriterion("ZIP is null");
            return (Criteria) this;
        }

        public Criteria andZipIsNotNull() {
            addCriterion("ZIP is not null");
            return (Criteria) this;
        }

        public Criteria andZipEqualTo(String value) {
            addCriterion("ZIP =", value, "zip");
            return (Criteria) this;
        }

        public Criteria andZipNotEqualTo(String value) {
            addCriterion("ZIP <>", value, "zip");
            return (Criteria) this;
        }

        public Criteria andZipGreaterThan(String value) {
            addCriterion("ZIP >", value, "zip");
            return (Criteria) this;
        }

        public Criteria andZipGreaterThanOrEqualTo(String value) {
            addCriterion("ZIP >=", value, "zip");
            return (Criteria) this;
        }

        public Criteria andZipLessThan(String value) {
            addCriterion("ZIP <", value, "zip");
            return (Criteria) this;
        }

        public Criteria andZipLessThanOrEqualTo(String value) {
            addCriterion("ZIP <=", value, "zip");
            return (Criteria) this;
        }

        public Criteria andZipLike(String value) {
            addCriterion("ZIP like", value, "zip");
            return (Criteria) this;
        }

        public Criteria andZipNotLike(String value) {
            addCriterion("ZIP not like", value, "zip");
            return (Criteria) this;
        }

        public Criteria andZipIn(List<String> values) {
            addCriterion("ZIP in", values, "zip");
            return (Criteria) this;
        }

        public Criteria andZipNotIn(List<String> values) {
            addCriterion("ZIP not in", values, "zip");
            return (Criteria) this;
        }

        public Criteria andZipBetween(String value1, String value2) {
            addCriterion("ZIP between", value1, value2, "zip");
            return (Criteria) this;
        }

        public Criteria andZipNotBetween(String value1, String value2) {
            addCriterion("ZIP not between", value1, value2, "zip");
            return (Criteria) this;
        }

        public Criteria andLatitudeIsNull() {
            addCriterion("LATITUDE is null");
            return (Criteria) this;
        }

        public Criteria andLatitudeIsNotNull() {
            addCriterion("LATITUDE is not null");
            return (Criteria) this;
        }

        public Criteria andLatitudeEqualTo(Double value) {
            addCriterion("LATITUDE =", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeNotEqualTo(Double value) {
            addCriterion("LATITUDE <>", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeGreaterThan(Double value) {
            addCriterion("LATITUDE >", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeGreaterThanOrEqualTo(Double value) {
            addCriterion("LATITUDE >=", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeLessThan(Double value) {
            addCriterion("LATITUDE <", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeLessThanOrEqualTo(Double value) {
            addCriterion("LATITUDE <=", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeIn(List<Double> values) {
            addCriterion("LATITUDE in", values, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeNotIn(List<Double> values) {
            addCriterion("LATITUDE not in", values, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeBetween(Double value1, Double value2) {
            addCriterion("LATITUDE between", value1, value2, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeNotBetween(Double value1, Double value2) {
            addCriterion("LATITUDE not between", value1, value2, "latitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeIsNull() {
            addCriterion("LONGITUDE is null");
            return (Criteria) this;
        }

        public Criteria andLongitudeIsNotNull() {
            addCriterion("LONGITUDE is not null");
            return (Criteria) this;
        }

        public Criteria andLongitudeEqualTo(Double value) {
            addCriterion("LONGITUDE =", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeNotEqualTo(Double value) {
            addCriterion("LONGITUDE <>", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeGreaterThan(Double value) {
            addCriterion("LONGITUDE >", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeGreaterThanOrEqualTo(Double value) {
            addCriterion("LONGITUDE >=", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeLessThan(Double value) {
            addCriterion("LONGITUDE <", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeLessThanOrEqualTo(Double value) {
            addCriterion("LONGITUDE <=", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeIn(List<Double> values) {
            addCriterion("LONGITUDE in", values, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeNotIn(List<Double> values) {
            addCriterion("LONGITUDE not in", values, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeBetween(Double value1, Double value2) {
            addCriterion("LONGITUDE between", value1, value2, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeNotBetween(Double value1, Double value2) {
            addCriterion("LONGITUDE not between", value1, value2, "longitude");
            return (Criteria) this;
        }

        public Criteria andTimezoneIsNull() {
            addCriterion("TIMEZONE is null");
            return (Criteria) this;
        }

        public Criteria andTimezoneIsNotNull() {
            addCriterion("TIMEZONE is not null");
            return (Criteria) this;
        }

        public Criteria andTimezoneEqualTo(String value) {
            addCriterion("TIMEZONE =", value, "timezone");
            return (Criteria) this;
        }

        public Criteria andTimezoneNotEqualTo(String value) {
            addCriterion("TIMEZONE <>", value, "timezone");
            return (Criteria) this;
        }

        public Criteria andTimezoneGreaterThan(String value) {
            addCriterion("TIMEZONE >", value, "timezone");
            return (Criteria) this;
        }

        public Criteria andTimezoneGreaterThanOrEqualTo(String value) {
            addCriterion("TIMEZONE >=", value, "timezone");
            return (Criteria) this;
        }

        public Criteria andTimezoneLessThan(String value) {
            addCriterion("TIMEZONE <", value, "timezone");
            return (Criteria) this;
        }

        public Criteria andTimezoneLessThanOrEqualTo(String value) {
            addCriterion("TIMEZONE <=", value, "timezone");
            return (Criteria) this;
        }

        public Criteria andTimezoneLike(String value) {
            addCriterion("TIMEZONE like", value, "timezone");
            return (Criteria) this;
        }

        public Criteria andTimezoneNotLike(String value) {
            addCriterion("TIMEZONE not like", value, "timezone");
            return (Criteria) this;
        }

        public Criteria andTimezoneIn(List<String> values) {
            addCriterion("TIMEZONE in", values, "timezone");
            return (Criteria) this;
        }

        public Criteria andTimezoneNotIn(List<String> values) {
            addCriterion("TIMEZONE not in", values, "timezone");
            return (Criteria) this;
        }

        public Criteria andTimezoneBetween(String value1, String value2) {
            addCriterion("TIMEZONE between", value1, value2, "timezone");
            return (Criteria) this;
        }

        public Criteria andTimezoneNotBetween(String value1, String value2) {
            addCriterion("TIMEZONE not between", value1, value2, "timezone");
            return (Criteria) this;
        }

        public Criteria andDepositIsNull() {
            addCriterion("DEPOSIT is null");
            return (Criteria) this;
        }

        public Criteria andDepositIsNotNull() {
            addCriterion("DEPOSIT is not null");
            return (Criteria) this;
        }

        public Criteria andDepositEqualTo(String value) {
            addCriterion("DEPOSIT =", value, "deposit");
            return (Criteria) this;
        }

        public Criteria andDepositNotEqualTo(String value) {
            addCriterion("DEPOSIT <>", value, "deposit");
            return (Criteria) this;
        }

        public Criteria andDepositGreaterThan(String value) {
            addCriterion("DEPOSIT >", value, "deposit");
            return (Criteria) this;
        }

        public Criteria andDepositGreaterThanOrEqualTo(String value) {
            addCriterion("DEPOSIT >=", value, "deposit");
            return (Criteria) this;
        }

        public Criteria andDepositLessThan(String value) {
            addCriterion("DEPOSIT <", value, "deposit");
            return (Criteria) this;
        }

        public Criteria andDepositLessThanOrEqualTo(String value) {
            addCriterion("DEPOSIT <=", value, "deposit");
            return (Criteria) this;
        }

        public Criteria andDepositLike(String value) {
            addCriterion("DEPOSIT like", value, "deposit");
            return (Criteria) this;
        }

        public Criteria andDepositNotLike(String value) {
            addCriterion("DEPOSIT not like", value, "deposit");
            return (Criteria) this;
        }

        public Criteria andDepositIn(List<String> values) {
            addCriterion("DEPOSIT in", values, "deposit");
            return (Criteria) this;
        }

        public Criteria andDepositNotIn(List<String> values) {
            addCriterion("DEPOSIT not in", values, "deposit");
            return (Criteria) this;
        }

        public Criteria andDepositBetween(String value1, String value2) {
            addCriterion("DEPOSIT between", value1, value2, "deposit");
            return (Criteria) this;
        }

        public Criteria andDepositNotBetween(String value1, String value2) {
            addCriterion("DEPOSIT not between", value1, value2, "deposit");
            return (Criteria) this;
        }

        public Criteria andBusinessHourIsNull() {
            addCriterion("BUSINESS_HOUR is null");
            return (Criteria) this;
        }

        public Criteria andBusinessHourIsNotNull() {
            addCriterion("BUSINESS_HOUR is not null");
            return (Criteria) this;
        }

        public Criteria andBusinessHourEqualTo(String value) {
            addCriterion("BUSINESS_HOUR =", value, "businessHour");
            return (Criteria) this;
        }

        public Criteria andBusinessHourNotEqualTo(String value) {
            addCriterion("BUSINESS_HOUR <>", value, "businessHour");
            return (Criteria) this;
        }

        public Criteria andBusinessHourGreaterThan(String value) {
            addCriterion("BUSINESS_HOUR >", value, "businessHour");
            return (Criteria) this;
        }

        public Criteria andBusinessHourGreaterThanOrEqualTo(String value) {
            addCriterion("BUSINESS_HOUR >=", value, "businessHour");
            return (Criteria) this;
        }

        public Criteria andBusinessHourLessThan(String value) {
            addCriterion("BUSINESS_HOUR <", value, "businessHour");
            return (Criteria) this;
        }

        public Criteria andBusinessHourLessThanOrEqualTo(String value) {
            addCriterion("BUSINESS_HOUR <=", value, "businessHour");
            return (Criteria) this;
        }

        public Criteria andBusinessHourLike(String value) {
            addCriterion("BUSINESS_HOUR like", value, "businessHour");
            return (Criteria) this;
        }

        public Criteria andBusinessHourNotLike(String value) {
            addCriterion("BUSINESS_HOUR not like", value, "businessHour");
            return (Criteria) this;
        }

        public Criteria andBusinessHourIn(List<String> values) {
            addCriterion("BUSINESS_HOUR in", values, "businessHour");
            return (Criteria) this;
        }

        public Criteria andBusinessHourNotIn(List<String> values) {
            addCriterion("BUSINESS_HOUR not in", values, "businessHour");
            return (Criteria) this;
        }

        public Criteria andBusinessHourBetween(String value1, String value2) {
            addCriterion("BUSINESS_HOUR between", value1, value2, "businessHour");
            return (Criteria) this;
        }

        public Criteria andBusinessHourNotBetween(String value1, String value2) {
            addCriterion("BUSINESS_HOUR not between", value1, value2, "businessHour");
            return (Criteria) this;
        }

        public Criteria andTipIsNull() {
            addCriterion("TIP is null");
            return (Criteria) this;
        }

        public Criteria andTipIsNotNull() {
            addCriterion("TIP is not null");
            return (Criteria) this;
        }

        public Criteria andTipEqualTo(String value) {
            addCriterion("TIP =", value, "tip");
            return (Criteria) this;
        }

        public Criteria andTipNotEqualTo(String value) {
            addCriterion("TIP <>", value, "tip");
            return (Criteria) this;
        }

        public Criteria andTipGreaterThan(String value) {
            addCriterion("TIP >", value, "tip");
            return (Criteria) this;
        }

        public Criteria andTipGreaterThanOrEqualTo(String value) {
            addCriterion("TIP >=", value, "tip");
            return (Criteria) this;
        }

        public Criteria andTipLessThan(String value) {
            addCriterion("TIP <", value, "tip");
            return (Criteria) this;
        }

        public Criteria andTipLessThanOrEqualTo(String value) {
            addCriterion("TIP <=", value, "tip");
            return (Criteria) this;
        }

        public Criteria andTipLike(String value) {
            addCriterion("TIP like", value, "tip");
            return (Criteria) this;
        }

        public Criteria andTipNotLike(String value) {
            addCriterion("TIP not like", value, "tip");
            return (Criteria) this;
        }

        public Criteria andTipIn(List<String> values) {
            addCriterion("TIP in", values, "tip");
            return (Criteria) this;
        }

        public Criteria andTipNotIn(List<String> values) {
            addCriterion("TIP not in", values, "tip");
            return (Criteria) this;
        }

        public Criteria andTipBetween(String value1, String value2) {
            addCriterion("TIP between", value1, value2, "tip");
            return (Criteria) this;
        }

        public Criteria andTipNotBetween(String value1, String value2) {
            addCriterion("TIP not between", value1, value2, "tip");
            return (Criteria) this;
        }

        public Criteria andIntroIsNull() {
            addCriterion("INTRO is null");
            return (Criteria) this;
        }

        public Criteria andIntroIsNotNull() {
            addCriterion("INTRO is not null");
            return (Criteria) this;
        }

        public Criteria andIntroEqualTo(String value) {
            addCriterion("INTRO =", value, "intro");
            return (Criteria) this;
        }

        public Criteria andIntroNotEqualTo(String value) {
            addCriterion("INTRO <>", value, "intro");
            return (Criteria) this;
        }

        public Criteria andIntroGreaterThan(String value) {
            addCriterion("INTRO >", value, "intro");
            return (Criteria) this;
        }

        public Criteria andIntroGreaterThanOrEqualTo(String value) {
            addCriterion("INTRO >=", value, "intro");
            return (Criteria) this;
        }

        public Criteria andIntroLessThan(String value) {
            addCriterion("INTRO <", value, "intro");
            return (Criteria) this;
        }

        public Criteria andIntroLessThanOrEqualTo(String value) {
            addCriterion("INTRO <=", value, "intro");
            return (Criteria) this;
        }

        public Criteria andIntroLike(String value) {
            addCriterion("INTRO like", value, "intro");
            return (Criteria) this;
        }

        public Criteria andIntroNotLike(String value) {
            addCriterion("INTRO not like", value, "intro");
            return (Criteria) this;
        }

        public Criteria andIntroIn(List<String> values) {
            addCriterion("INTRO in", values, "intro");
            return (Criteria) this;
        }

        public Criteria andIntroNotIn(List<String> values) {
            addCriterion("INTRO not in", values, "intro");
            return (Criteria) this;
        }

        public Criteria andIntroBetween(String value1, String value2) {
            addCriterion("INTRO between", value1, value2, "intro");
            return (Criteria) this;
        }

        public Criteria andIntroNotBetween(String value1, String value2) {
            addCriterion("INTRO not between", value1, value2, "intro");
            return (Criteria) this;
        }

        public Criteria andAdminIdIsNull() {
            addCriterion("ADMIN_ID is null");
            return (Criteria) this;
        }

        public Criteria andAdminIdIsNotNull() {
            addCriterion("ADMIN_ID is not null");
            return (Criteria) this;
        }

        public Criteria andAdminIdEqualTo(String value) {
            addCriterion("ADMIN_ID =", value, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdNotEqualTo(String value) {
            addCriterion("ADMIN_ID <>", value, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdGreaterThan(String value) {
            addCriterion("ADMIN_ID >", value, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdGreaterThanOrEqualTo(String value) {
            addCriterion("ADMIN_ID >=", value, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdLessThan(String value) {
            addCriterion("ADMIN_ID <", value, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdLessThanOrEqualTo(String value) {
            addCriterion("ADMIN_ID <=", value, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdLike(String value) {
            addCriterion("ADMIN_ID like", value, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdNotLike(String value) {
            addCriterion("ADMIN_ID not like", value, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdIn(List<String> values) {
            addCriterion("ADMIN_ID in", values, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdNotIn(List<String> values) {
            addCriterion("ADMIN_ID not in", values, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdBetween(String value1, String value2) {
            addCriterion("ADMIN_ID between", value1, value2, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdNotBetween(String value1, String value2) {
            addCriterion("ADMIN_ID not between", value1, value2, "adminId");
            return (Criteria) this;
        }

        public Criteria andHasNvrIsNull() {
            addCriterion("HAS_NVR is null");
            return (Criteria) this;
        }

        public Criteria andHasNvrIsNotNull() {
            addCriterion("HAS_NVR is not null");
            return (Criteria) this;
        }

        public Criteria andHasNvrEqualTo(Boolean value) {
            addCriterion("HAS_NVR =", value, "hasNvr");
            return (Criteria) this;
        }

        public Criteria andHasNvrNotEqualTo(Boolean value) {
            addCriterion("HAS_NVR <>", value, "hasNvr");
            return (Criteria) this;
        }

        public Criteria andHasNvrGreaterThan(Boolean value) {
            addCriterion("HAS_NVR >", value, "hasNvr");
            return (Criteria) this;
        }

        public Criteria andHasNvrGreaterThanOrEqualTo(Boolean value) {
            addCriterion("HAS_NVR >=", value, "hasNvr");
            return (Criteria) this;
        }

        public Criteria andHasNvrLessThan(Boolean value) {
            addCriterion("HAS_NVR <", value, "hasNvr");
            return (Criteria) this;
        }

        public Criteria andHasNvrLessThanOrEqualTo(Boolean value) {
            addCriterion("HAS_NVR <=", value, "hasNvr");
            return (Criteria) this;
        }

        public Criteria andHasNvrIn(List<Boolean> values) {
            addCriterion("HAS_NVR in", values, "hasNvr");
            return (Criteria) this;
        }

        public Criteria andHasNvrNotIn(List<Boolean> values) {
            addCriterion("HAS_NVR not in", values, "hasNvr");
            return (Criteria) this;
        }

        public Criteria andHasNvrBetween(Boolean value1, Boolean value2) {
            addCriterion("HAS_NVR between", value1, value2, "hasNvr");
            return (Criteria) this;
        }

        public Criteria andHasNvrNotBetween(Boolean value1, Boolean value2) {
            addCriterion("HAS_NVR not between", value1, value2, "hasNvr");
            return (Criteria) this;
        }

        public Criteria andCreatedIsNull() {
            addCriterion("CREATED is null");
            return (Criteria) this;
        }

        public Criteria andCreatedIsNotNull() {
            addCriterion("CREATED is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedEqualTo(Date value) {
            addCriterion("CREATED =", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedNotEqualTo(Date value) {
            addCriterion("CREATED <>", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedGreaterThan(Date value) {
            addCriterion("CREATED >", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATED >=", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedLessThan(Date value) {
            addCriterion("CREATED <", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedLessThanOrEqualTo(Date value) {
            addCriterion("CREATED <=", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedIn(List<Date> values) {
            addCriterion("CREATED in", values, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedNotIn(List<Date> values) {
            addCriterion("CREATED not in", values, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedBetween(Date value1, Date value2) {
            addCriterion("CREATED between", value1, value2, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedNotBetween(Date value1, Date value2) {
            addCriterion("CREATED not between", value1, value2, "created");
            return (Criteria) this;
        }

        public Criteria andUpdatedIsNull() {
            addCriterion("UPDATED is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedIsNotNull() {
            addCriterion("UPDATED is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedEqualTo(Date value) {
            addCriterion("UPDATED =", value, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedNotEqualTo(Date value) {
            addCriterion("UPDATED <>", value, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedGreaterThan(Date value) {
            addCriterion("UPDATED >", value, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATED >=", value, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedLessThan(Date value) {
            addCriterion("UPDATED <", value, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedLessThanOrEqualTo(Date value) {
            addCriterion("UPDATED <=", value, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedIn(List<Date> values) {
            addCriterion("UPDATED in", values, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedNotIn(List<Date> values) {
            addCriterion("UPDATED not in", values, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedBetween(Date value1, Date value2) {
            addCriterion("UPDATED between", value1, value2, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedNotBetween(Date value1, Date value2) {
            addCriterion("UPDATED not between", value1, value2, "updated");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_svc_store
     *
     * @mbggenerated do_not_delete_during_merge Thu Aug 04 11:39:46 KST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_svc_store
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}