package com.jc.pico.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SvcSalesItemOptExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_svc_sales_item_opt
     *
     * @mbggenerated Mon Dec 26 10:42:58 KST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_svc_sales_item_opt
     *
     * @mbggenerated Mon Dec 26 10:42:58 KST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_svc_sales_item_opt
     *
     * @mbggenerated Mon Dec 26 10:42:58 KST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_sales_item_opt
     *
     * @mbggenerated Mon Dec 26 10:42:58 KST 2016
     */
    public SvcSalesItemOptExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_sales_item_opt
     *
     * @mbggenerated Mon Dec 26 10:42:58 KST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_sales_item_opt
     *
     * @mbggenerated Mon Dec 26 10:42:58 KST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_sales_item_opt
     *
     * @mbggenerated Mon Dec 26 10:42:58 KST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_sales_item_opt
     *
     * @mbggenerated Mon Dec 26 10:42:58 KST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_sales_item_opt
     *
     * @mbggenerated Mon Dec 26 10:42:58 KST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_sales_item_opt
     *
     * @mbggenerated Mon Dec 26 10:42:58 KST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_sales_item_opt
     *
     * @mbggenerated Mon Dec 26 10:42:58 KST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_sales_item_opt
     *
     * @mbggenerated Mon Dec 26 10:42:58 KST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_sales_item_opt
     *
     * @mbggenerated Mon Dec 26 10:42:58 KST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_sales_item_opt
     *
     * @mbggenerated Mon Dec 26 10:42:58 KST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_svc_sales_item_opt
     *
     * @mbggenerated Mon Dec 26 10:42:58 KST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSalesIdIsNull() {
            addCriterion("SALES_ID is null");
            return (Criteria) this;
        }

        public Criteria andSalesIdIsNotNull() {
            addCriterion("SALES_ID is not null");
            return (Criteria) this;
        }

        public Criteria andSalesIdEqualTo(Long value) {
            addCriterion("SALES_ID =", value, "salesId");
            return (Criteria) this;
        }

        public Criteria andSalesIdNotEqualTo(Long value) {
            addCriterion("SALES_ID <>", value, "salesId");
            return (Criteria) this;
        }

        public Criteria andSalesIdGreaterThan(Long value) {
            addCriterion("SALES_ID >", value, "salesId");
            return (Criteria) this;
        }

        public Criteria andSalesIdGreaterThanOrEqualTo(Long value) {
            addCriterion("SALES_ID >=", value, "salesId");
            return (Criteria) this;
        }

        public Criteria andSalesIdLessThan(Long value) {
            addCriterion("SALES_ID <", value, "salesId");
            return (Criteria) this;
        }

        public Criteria andSalesIdLessThanOrEqualTo(Long value) {
            addCriterion("SALES_ID <=", value, "salesId");
            return (Criteria) this;
        }

        public Criteria andSalesIdIn(List<Long> values) {
            addCriterion("SALES_ID in", values, "salesId");
            return (Criteria) this;
        }

        public Criteria andSalesIdNotIn(List<Long> values) {
            addCriterion("SALES_ID not in", values, "salesId");
            return (Criteria) this;
        }

        public Criteria andSalesIdBetween(Long value1, Long value2) {
            addCriterion("SALES_ID between", value1, value2, "salesId");
            return (Criteria) this;
        }

        public Criteria andSalesIdNotBetween(Long value1, Long value2) {
            addCriterion("SALES_ID not between", value1, value2, "salesId");
            return (Criteria) this;
        }

        public Criteria andItemIdIsNull() {
            addCriterion("ITEM_ID is null");
            return (Criteria) this;
        }

        public Criteria andItemIdIsNotNull() {
            addCriterion("ITEM_ID is not null");
            return (Criteria) this;
        }

        public Criteria andItemIdEqualTo(Long value) {
            addCriterion("ITEM_ID =", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdNotEqualTo(Long value) {
            addCriterion("ITEM_ID <>", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdGreaterThan(Long value) {
            addCriterion("ITEM_ID >", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ITEM_ID >=", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdLessThan(Long value) {
            addCriterion("ITEM_ID <", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdLessThanOrEqualTo(Long value) {
            addCriterion("ITEM_ID <=", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdIn(List<Long> values) {
            addCriterion("ITEM_ID in", values, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdNotIn(List<Long> values) {
            addCriterion("ITEM_ID not in", values, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdBetween(Long value1, Long value2) {
            addCriterion("ITEM_ID between", value1, value2, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdNotBetween(Long value1, Long value2) {
            addCriterion("ITEM_ID not between", value1, value2, "itemId");
            return (Criteria) this;
        }

        public Criteria andOrdinalIsNull() {
            addCriterion("ORDINAL is null");
            return (Criteria) this;
        }

        public Criteria andOrdinalIsNotNull() {
            addCriterion("ORDINAL is not null");
            return (Criteria) this;
        }

        public Criteria andOrdinalEqualTo(Long value) {
            addCriterion("ORDINAL =", value, "ordinal");
            return (Criteria) this;
        }

        public Criteria andOrdinalNotEqualTo(Long value) {
            addCriterion("ORDINAL <>", value, "ordinal");
            return (Criteria) this;
        }

        public Criteria andOrdinalGreaterThan(Long value) {
            addCriterion("ORDINAL >", value, "ordinal");
            return (Criteria) this;
        }

        public Criteria andOrdinalGreaterThanOrEqualTo(Long value) {
            addCriterion("ORDINAL >=", value, "ordinal");
            return (Criteria) this;
        }

        public Criteria andOrdinalLessThan(Long value) {
            addCriterion("ORDINAL <", value, "ordinal");
            return (Criteria) this;
        }

        public Criteria andOrdinalLessThanOrEqualTo(Long value) {
            addCriterion("ORDINAL <=", value, "ordinal");
            return (Criteria) this;
        }

        public Criteria andOrdinalIn(List<Long> values) {
            addCriterion("ORDINAL in", values, "ordinal");
            return (Criteria) this;
        }

        public Criteria andOrdinalNotIn(List<Long> values) {
            addCriterion("ORDINAL not in", values, "ordinal");
            return (Criteria) this;
        }

        public Criteria andOrdinalBetween(Long value1, Long value2) {
            addCriterion("ORDINAL between", value1, value2, "ordinal");
            return (Criteria) this;
        }

        public Criteria andOrdinalNotBetween(Long value1, Long value2) {
            addCriterion("ORDINAL not between", value1, value2, "ordinal");
            return (Criteria) this;
        }

        public Criteria andOptIdIsNull() {
            addCriterion("OPT_ID is null");
            return (Criteria) this;
        }

        public Criteria andOptIdIsNotNull() {
            addCriterion("OPT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andOptIdEqualTo(Long value) {
            addCriterion("OPT_ID =", value, "optId");
            return (Criteria) this;
        }

        public Criteria andOptIdNotEqualTo(Long value) {
            addCriterion("OPT_ID <>", value, "optId");
            return (Criteria) this;
        }

        public Criteria andOptIdGreaterThan(Long value) {
            addCriterion("OPT_ID >", value, "optId");
            return (Criteria) this;
        }

        public Criteria andOptIdGreaterThanOrEqualTo(Long value) {
            addCriterion("OPT_ID >=", value, "optId");
            return (Criteria) this;
        }

        public Criteria andOptIdLessThan(Long value) {
            addCriterion("OPT_ID <", value, "optId");
            return (Criteria) this;
        }

        public Criteria andOptIdLessThanOrEqualTo(Long value) {
            addCriterion("OPT_ID <=", value, "optId");
            return (Criteria) this;
        }

        public Criteria andOptIdIn(List<Long> values) {
            addCriterion("OPT_ID in", values, "optId");
            return (Criteria) this;
        }

        public Criteria andOptIdNotIn(List<Long> values) {
            addCriterion("OPT_ID not in", values, "optId");
            return (Criteria) this;
        }

        public Criteria andOptIdBetween(Long value1, Long value2) {
            addCriterion("OPT_ID between", value1, value2, "optId");
            return (Criteria) this;
        }

        public Criteria andOptIdNotBetween(Long value1, Long value2) {
            addCriterion("OPT_ID not between", value1, value2, "optId");
            return (Criteria) this;
        }

        public Criteria andOptDtlIdIsNull() {
            addCriterion("OPT_DTL_ID is null");
            return (Criteria) this;
        }

        public Criteria andOptDtlIdIsNotNull() {
            addCriterion("OPT_DTL_ID is not null");
            return (Criteria) this;
        }

        public Criteria andOptDtlIdEqualTo(Long value) {
            addCriterion("OPT_DTL_ID =", value, "optDtlId");
            return (Criteria) this;
        }

        public Criteria andOptDtlIdNotEqualTo(Long value) {
            addCriterion("OPT_DTL_ID <>", value, "optDtlId");
            return (Criteria) this;
        }

        public Criteria andOptDtlIdGreaterThan(Long value) {
            addCriterion("OPT_DTL_ID >", value, "optDtlId");
            return (Criteria) this;
        }

        public Criteria andOptDtlIdGreaterThanOrEqualTo(Long value) {
            addCriterion("OPT_DTL_ID >=", value, "optDtlId");
            return (Criteria) this;
        }

        public Criteria andOptDtlIdLessThan(Long value) {
            addCriterion("OPT_DTL_ID <", value, "optDtlId");
            return (Criteria) this;
        }

        public Criteria andOptDtlIdLessThanOrEqualTo(Long value) {
            addCriterion("OPT_DTL_ID <=", value, "optDtlId");
            return (Criteria) this;
        }

        public Criteria andOptDtlIdIn(List<Long> values) {
            addCriterion("OPT_DTL_ID in", values, "optDtlId");
            return (Criteria) this;
        }

        public Criteria andOptDtlIdNotIn(List<Long> values) {
            addCriterion("OPT_DTL_ID not in", values, "optDtlId");
            return (Criteria) this;
        }

        public Criteria andOptDtlIdBetween(Long value1, Long value2) {
            addCriterion("OPT_DTL_ID between", value1, value2, "optDtlId");
            return (Criteria) this;
        }

        public Criteria andOptDtlIdNotBetween(Long value1, Long value2) {
            addCriterion("OPT_DTL_ID not between", value1, value2, "optDtlId");
            return (Criteria) this;
        }

        public Criteria andOptNmIsNull() {
            addCriterion("OPT_NM is null");
            return (Criteria) this;
        }

        public Criteria andOptNmIsNotNull() {
            addCriterion("OPT_NM is not null");
            return (Criteria) this;
        }

        public Criteria andOptNmEqualTo(String value) {
            addCriterion("OPT_NM =", value, "optNm");
            return (Criteria) this;
        }

        public Criteria andOptNmNotEqualTo(String value) {
            addCriterion("OPT_NM <>", value, "optNm");
            return (Criteria) this;
        }

        public Criteria andOptNmGreaterThan(String value) {
            addCriterion("OPT_NM >", value, "optNm");
            return (Criteria) this;
        }

        public Criteria andOptNmGreaterThanOrEqualTo(String value) {
            addCriterion("OPT_NM >=", value, "optNm");
            return (Criteria) this;
        }

        public Criteria andOptNmLessThan(String value) {
            addCriterion("OPT_NM <", value, "optNm");
            return (Criteria) this;
        }

        public Criteria andOptNmLessThanOrEqualTo(String value) {
            addCriterion("OPT_NM <=", value, "optNm");
            return (Criteria) this;
        }

        public Criteria andOptNmLike(String value) {
            addCriterion("OPT_NM like", value, "optNm");
            return (Criteria) this;
        }

        public Criteria andOptNmNotLike(String value) {
            addCriterion("OPT_NM not like", value, "optNm");
            return (Criteria) this;
        }

        public Criteria andOptNmIn(List<String> values) {
            addCriterion("OPT_NM in", values, "optNm");
            return (Criteria) this;
        }

        public Criteria andOptNmNotIn(List<String> values) {
            addCriterion("OPT_NM not in", values, "optNm");
            return (Criteria) this;
        }

        public Criteria andOptNmBetween(String value1, String value2) {
            addCriterion("OPT_NM between", value1, value2, "optNm");
            return (Criteria) this;
        }

        public Criteria andOptNmNotBetween(String value1, String value2) {
            addCriterion("OPT_NM not between", value1, value2, "optNm");
            return (Criteria) this;
        }

        public Criteria andOptDtlNmIsNull() {
            addCriterion("OPT_DTL_NM is null");
            return (Criteria) this;
        }

        public Criteria andOptDtlNmIsNotNull() {
            addCriterion("OPT_DTL_NM is not null");
            return (Criteria) this;
        }

        public Criteria andOptDtlNmEqualTo(String value) {
            addCriterion("OPT_DTL_NM =", value, "optDtlNm");
            return (Criteria) this;
        }

        public Criteria andOptDtlNmNotEqualTo(String value) {
            addCriterion("OPT_DTL_NM <>", value, "optDtlNm");
            return (Criteria) this;
        }

        public Criteria andOptDtlNmGreaterThan(String value) {
            addCriterion("OPT_DTL_NM >", value, "optDtlNm");
            return (Criteria) this;
        }

        public Criteria andOptDtlNmGreaterThanOrEqualTo(String value) {
            addCriterion("OPT_DTL_NM >=", value, "optDtlNm");
            return (Criteria) this;
        }

        public Criteria andOptDtlNmLessThan(String value) {
            addCriterion("OPT_DTL_NM <", value, "optDtlNm");
            return (Criteria) this;
        }

        public Criteria andOptDtlNmLessThanOrEqualTo(String value) {
            addCriterion("OPT_DTL_NM <=", value, "optDtlNm");
            return (Criteria) this;
        }

        public Criteria andOptDtlNmLike(String value) {
            addCriterion("OPT_DTL_NM like", value, "optDtlNm");
            return (Criteria) this;
        }

        public Criteria andOptDtlNmNotLike(String value) {
            addCriterion("OPT_DTL_NM not like", value, "optDtlNm");
            return (Criteria) this;
        }

        public Criteria andOptDtlNmIn(List<String> values) {
            addCriterion("OPT_DTL_NM in", values, "optDtlNm");
            return (Criteria) this;
        }

        public Criteria andOptDtlNmNotIn(List<String> values) {
            addCriterion("OPT_DTL_NM not in", values, "optDtlNm");
            return (Criteria) this;
        }

        public Criteria andOptDtlNmBetween(String value1, String value2) {
            addCriterion("OPT_DTL_NM between", value1, value2, "optDtlNm");
            return (Criteria) this;
        }

        public Criteria andOptDtlNmNotBetween(String value1, String value2) {
            addCriterion("OPT_DTL_NM not between", value1, value2, "optDtlNm");
            return (Criteria) this;
        }

        public Criteria andOptPriceIsNull() {
            addCriterion("OPT_PRICE is null");
            return (Criteria) this;
        }

        public Criteria andOptPriceIsNotNull() {
            addCriterion("OPT_PRICE is not null");
            return (Criteria) this;
        }

        public Criteria andOptPriceEqualTo(Double value) {
            addCriterion("OPT_PRICE =", value, "optPrice");
            return (Criteria) this;
        }

        public Criteria andOptPriceNotEqualTo(Double value) {
            addCriterion("OPT_PRICE <>", value, "optPrice");
            return (Criteria) this;
        }

        public Criteria andOptPriceGreaterThan(Double value) {
            addCriterion("OPT_PRICE >", value, "optPrice");
            return (Criteria) this;
        }

        public Criteria andOptPriceGreaterThanOrEqualTo(Double value) {
            addCriterion("OPT_PRICE >=", value, "optPrice");
            return (Criteria) this;
        }

        public Criteria andOptPriceLessThan(Double value) {
            addCriterion("OPT_PRICE <", value, "optPrice");
            return (Criteria) this;
        }

        public Criteria andOptPriceLessThanOrEqualTo(Double value) {
            addCriterion("OPT_PRICE <=", value, "optPrice");
            return (Criteria) this;
        }

        public Criteria andOptPriceIn(List<Double> values) {
            addCriterion("OPT_PRICE in", values, "optPrice");
            return (Criteria) this;
        }

        public Criteria andOptPriceNotIn(List<Double> values) {
            addCriterion("OPT_PRICE not in", values, "optPrice");
            return (Criteria) this;
        }

        public Criteria andOptPriceBetween(Double value1, Double value2) {
            addCriterion("OPT_PRICE between", value1, value2, "optPrice");
            return (Criteria) this;
        }

        public Criteria andOptPriceNotBetween(Double value1, Double value2) {
            addCriterion("OPT_PRICE not between", value1, value2, "optPrice");
            return (Criteria) this;
        }

        public Criteria andCreatedIsNull() {
            addCriterion("CREATED is null");
            return (Criteria) this;
        }

        public Criteria andCreatedIsNotNull() {
            addCriterion("CREATED is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedEqualTo(Date value) {
            addCriterion("CREATED =", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedNotEqualTo(Date value) {
            addCriterion("CREATED <>", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedGreaterThan(Date value) {
            addCriterion("CREATED >", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATED >=", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedLessThan(Date value) {
            addCriterion("CREATED <", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedLessThanOrEqualTo(Date value) {
            addCriterion("CREATED <=", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedIn(List<Date> values) {
            addCriterion("CREATED in", values, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedNotIn(List<Date> values) {
            addCriterion("CREATED not in", values, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedBetween(Date value1, Date value2) {
            addCriterion("CREATED between", value1, value2, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedNotBetween(Date value1, Date value2) {
            addCriterion("CREATED not between", value1, value2, "created");
            return (Criteria) this;
        }

        public Criteria andUpdatedIsNull() {
            addCriterion("UPDATED is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedIsNotNull() {
            addCriterion("UPDATED is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedEqualTo(Date value) {
            addCriterion("UPDATED =", value, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedNotEqualTo(Date value) {
            addCriterion("UPDATED <>", value, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedGreaterThan(Date value) {
            addCriterion("UPDATED >", value, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATED >=", value, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedLessThan(Date value) {
            addCriterion("UPDATED <", value, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedLessThanOrEqualTo(Date value) {
            addCriterion("UPDATED <=", value, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedIn(List<Date> values) {
            addCriterion("UPDATED in", values, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedNotIn(List<Date> values) {
            addCriterion("UPDATED not in", values, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedBetween(Date value1, Date value2) {
            addCriterion("UPDATED between", value1, value2, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedNotBetween(Date value1, Date value2) {
            addCriterion("UPDATED not between", value1, value2, "updated");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_svc_sales_item_opt
     *
     * @mbggenerated do_not_delete_during_merge Mon Dec 26 10:42:58 KST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_svc_sales_item_opt
     *
     * @mbggenerated Mon Dec 26 10:42:58 KST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}