package com.jc.pico.bean;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.Date;

@JsonIgnoreProperties(ignoreUnknown = true)
public class SvcSalesPay {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_svc_sales_pay.ID
     *
     * @mbggenerated Fri Jan 06 17:22:42 KST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_svc_sales_pay.SALES_ID
     *
     * @mbggenerated Fri Jan 06 17:22:42 KST 2017
     */
    private Long salesId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_svc_sales_pay.STAFF_ID
     *
     * @mbggenerated Fri Jan 06 17:22:42 KST 2017
     */
    private Long staffId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_svc_sales_pay.SALES_ST
     *
     * @mbggenerated Fri Jan 06 17:22:42 KST 2017
     */
    private String salesSt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_svc_sales_pay.ORDINAL
     *
     * @mbggenerated Fri Jan 06 17:22:42 KST 2017
     */
    private Long ordinal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_svc_sales_pay.PARTIAL_ORDINAL
     *
     * @mbggenerated Fri Jan 06 17:22:42 KST 2017
     */
    private Long partialOrdinal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_svc_sales_pay.PAY_METHOD
     *
     * @mbggenerated Fri Jan 06 17:22:42 KST 2017
     */
    private String payMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_svc_sales_pay.CARD_NO
     *
     * @mbggenerated Fri Jan 06 17:22:42 KST 2017
     */
    private String cardNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_svc_sales_pay.AMOUNT
     *
     * @mbggenerated Fri Jan 06 17:22:42 KST 2017
     */
    private Double amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_svc_sales_pay.PAY_TM
     *
     * @mbggenerated Fri Jan 06 17:22:42 KST 2017
     */
    private Date payTm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_svc_sales_pay.PAY_TM_LOCAL
     *
     * @mbggenerated Fri Jan 06 17:22:42 KST 2017
     */
    private Date payTmLocal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_svc_sales_pay.TRAN_NO
     *
     * @mbggenerated Fri Jan 06 17:22:42 KST 2017
     */
    private String tranNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_svc_sales_pay.MONTHLY_PLAIN
     *
     * @mbggenerated Fri Jan 06 17:22:42 KST 2017
     */
    private Byte monthlyPlain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_svc_sales_pay.PG_KIND
     *
     * @mbggenerated Fri Jan 06 17:22:42 KST 2017
     */
    private String pgKind;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_svc_sales_pay.CREATED
     *
     * @mbggenerated Fri Jan 06 17:22:42 KST 2017
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_svc_sales_pay.UPDATED
     *
     * @mbggenerated Fri Jan 06 17:22:42 KST 2017
     */
    private Date updated;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_svc_sales_pay.ID
     *
     * @return the value of tb_svc_sales_pay.ID
     *
     * @mbggenerated Fri Jan 06 17:22:42 KST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_svc_sales_pay.ID
     *
     * @param id the value for tb_svc_sales_pay.ID
     *
     * @mbggenerated Fri Jan 06 17:22:42 KST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_svc_sales_pay.SALES_ID
     *
     * @return the value of tb_svc_sales_pay.SALES_ID
     *
     * @mbggenerated Fri Jan 06 17:22:42 KST 2017
     */
    public Long getSalesId() {
        return salesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_svc_sales_pay.SALES_ID
     *
     * @param salesId the value for tb_svc_sales_pay.SALES_ID
     *
     * @mbggenerated Fri Jan 06 17:22:42 KST 2017
     */
    public void setSalesId(Long salesId) {
        this.salesId = salesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_svc_sales_pay.STAFF_ID
     *
     * @return the value of tb_svc_sales_pay.STAFF_ID
     *
     * @mbggenerated Fri Jan 06 17:22:42 KST 2017
     */
    public Long getStaffId() {
        return staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_svc_sales_pay.STAFF_ID
     *
     * @param staffId the value for tb_svc_sales_pay.STAFF_ID
     *
     * @mbggenerated Fri Jan 06 17:22:42 KST 2017
     */
    public void setStaffId(Long staffId) {
        this.staffId = staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_svc_sales_pay.SALES_ST
     *
     * @return the value of tb_svc_sales_pay.SALES_ST
     *
     * @mbggenerated Fri Jan 06 17:22:42 KST 2017
     */
    public String getSalesSt() {
        return salesSt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_svc_sales_pay.SALES_ST
     *
     * @param salesSt the value for tb_svc_sales_pay.SALES_ST
     *
     * @mbggenerated Fri Jan 06 17:22:42 KST 2017
     */
    public void setSalesSt(String salesSt) {
        this.salesSt = salesSt == null ? null : salesSt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_svc_sales_pay.ORDINAL
     *
     * @return the value of tb_svc_sales_pay.ORDINAL
     *
     * @mbggenerated Fri Jan 06 17:22:42 KST 2017
     */
    public Long getOrdinal() {
        return ordinal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_svc_sales_pay.ORDINAL
     *
     * @param ordinal the value for tb_svc_sales_pay.ORDINAL
     *
     * @mbggenerated Fri Jan 06 17:22:42 KST 2017
     */
    public void setOrdinal(Long ordinal) {
        this.ordinal = ordinal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_svc_sales_pay.PARTIAL_ORDINAL
     *
     * @return the value of tb_svc_sales_pay.PARTIAL_ORDINAL
     *
     * @mbggenerated Fri Jan 06 17:22:42 KST 2017
     */
    public Long getPartialOrdinal() {
        return partialOrdinal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_svc_sales_pay.PARTIAL_ORDINAL
     *
     * @param partialOrdinal the value for tb_svc_sales_pay.PARTIAL_ORDINAL
     *
     * @mbggenerated Fri Jan 06 17:22:42 KST 2017
     */
    public void setPartialOrdinal(Long partialOrdinal) {
        this.partialOrdinal = partialOrdinal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_svc_sales_pay.PAY_METHOD
     *
     * @return the value of tb_svc_sales_pay.PAY_METHOD
     *
     * @mbggenerated Fri Jan 06 17:22:42 KST 2017
     */
    public String getPayMethod() {
        return payMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_svc_sales_pay.PAY_METHOD
     *
     * @param payMethod the value for tb_svc_sales_pay.PAY_METHOD
     *
     * @mbggenerated Fri Jan 06 17:22:42 KST 2017
     */
    public void setPayMethod(String payMethod) {
        this.payMethod = payMethod == null ? null : payMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_svc_sales_pay.CARD_NO
     *
     * @return the value of tb_svc_sales_pay.CARD_NO
     *
     * @mbggenerated Fri Jan 06 17:22:42 KST 2017
     */
    public String getCardNo() {
        return cardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_svc_sales_pay.CARD_NO
     *
     * @param cardNo the value for tb_svc_sales_pay.CARD_NO
     *
     * @mbggenerated Fri Jan 06 17:22:42 KST 2017
     */
    public void setCardNo(String cardNo) {
        this.cardNo = cardNo == null ? null : cardNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_svc_sales_pay.AMOUNT
     *
     * @return the value of tb_svc_sales_pay.AMOUNT
     *
     * @mbggenerated Fri Jan 06 17:22:42 KST 2017
     */
    public Double getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_svc_sales_pay.AMOUNT
     *
     * @param amount the value for tb_svc_sales_pay.AMOUNT
     *
     * @mbggenerated Fri Jan 06 17:22:42 KST 2017
     */
    public void setAmount(Double amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_svc_sales_pay.PAY_TM
     *
     * @return the value of tb_svc_sales_pay.PAY_TM
     *
     * @mbggenerated Fri Jan 06 17:22:42 KST 2017
     */
    public Date getPayTm() {
        return payTm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_svc_sales_pay.PAY_TM
     *
     * @param payTm the value for tb_svc_sales_pay.PAY_TM
     *
     * @mbggenerated Fri Jan 06 17:22:42 KST 2017
     */
    public void setPayTm(Date payTm) {
        this.payTm = payTm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_svc_sales_pay.PAY_TM_LOCAL
     *
     * @return the value of tb_svc_sales_pay.PAY_TM_LOCAL
     *
     * @mbggenerated Fri Jan 06 17:22:42 KST 2017
     */
    public Date getPayTmLocal() {
        return payTmLocal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_svc_sales_pay.PAY_TM_LOCAL
     *
     * @param payTmLocal the value for tb_svc_sales_pay.PAY_TM_LOCAL
     *
     * @mbggenerated Fri Jan 06 17:22:42 KST 2017
     */
    public void setPayTmLocal(Date payTmLocal) {
        this.payTmLocal = payTmLocal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_svc_sales_pay.TRAN_NO
     *
     * @return the value of tb_svc_sales_pay.TRAN_NO
     *
     * @mbggenerated Fri Jan 06 17:22:42 KST 2017
     */
    public String getTranNo() {
        return tranNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_svc_sales_pay.TRAN_NO
     *
     * @param tranNo the value for tb_svc_sales_pay.TRAN_NO
     *
     * @mbggenerated Fri Jan 06 17:22:42 KST 2017
     */
    public void setTranNo(String tranNo) {
        this.tranNo = tranNo == null ? null : tranNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_svc_sales_pay.MONTHLY_PLAIN
     *
     * @return the value of tb_svc_sales_pay.MONTHLY_PLAIN
     *
     * @mbggenerated Fri Jan 06 17:22:42 KST 2017
     */
    public Byte getMonthlyPlain() {
        return monthlyPlain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_svc_sales_pay.MONTHLY_PLAIN
     *
     * @param monthlyPlain the value for tb_svc_sales_pay.MONTHLY_PLAIN
     *
     * @mbggenerated Fri Jan 06 17:22:42 KST 2017
     */
    public void setMonthlyPlain(Byte monthlyPlain) {
        this.monthlyPlain = monthlyPlain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_svc_sales_pay.PG_KIND
     *
     * @return the value of tb_svc_sales_pay.PG_KIND
     *
     * @mbggenerated Fri Jan 06 17:22:42 KST 2017
     */
    public String getPgKind() {
        return pgKind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_svc_sales_pay.PG_KIND
     *
     * @param pgKind the value for tb_svc_sales_pay.PG_KIND
     *
     * @mbggenerated Fri Jan 06 17:22:42 KST 2017
     */
    public void setPgKind(String pgKind) {
        this.pgKind = pgKind == null ? null : pgKind.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_svc_sales_pay.CREATED
     *
     * @return the value of tb_svc_sales_pay.CREATED
     *
     * @mbggenerated Fri Jan 06 17:22:42 KST 2017
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_svc_sales_pay.CREATED
     *
     * @param created the value for tb_svc_sales_pay.CREATED
     *
     * @mbggenerated Fri Jan 06 17:22:42 KST 2017
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_svc_sales_pay.UPDATED
     *
     * @return the value of tb_svc_sales_pay.UPDATED
     *
     * @mbggenerated Fri Jan 06 17:22:42 KST 2017
     */
    public Date getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_svc_sales_pay.UPDATED
     *
     * @param updated the value for tb_svc_sales_pay.UPDATED
     *
     * @mbggenerated Fri Jan 06 17:22:42 KST 2017
     */
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
}