package com.jc.pico.bean;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.Date;

@JsonIgnoreProperties(ignoreUnknown = true)
public class UserNoti {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_noti.ID
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_noti.USER_ID
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_noti.BRAND_ID
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    private Long brandId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_noti.NOTI_TP
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    private String notiTp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_noti.OPT_TP
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    private String optTp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_noti.USED
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    private Boolean used;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_noti.CREATED
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_noti.UPDATED
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    private Date updated;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_noti.ID
     *
     * @return the value of tb_user_noti.ID
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_noti.ID
     *
     * @param id the value for tb_user_noti.ID
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_noti.USER_ID
     *
     * @return the value of tb_user_noti.USER_ID
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_noti.USER_ID
     *
     * @param userId the value for tb_user_noti.USER_ID
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_noti.BRAND_ID
     *
     * @return the value of tb_user_noti.BRAND_ID
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    public Long getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_noti.BRAND_ID
     *
     * @param brandId the value for tb_user_noti.BRAND_ID
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    public void setBrandId(Long brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_noti.NOTI_TP
     *
     * @return the value of tb_user_noti.NOTI_TP
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    public String getNotiTp() {
        return notiTp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_noti.NOTI_TP
     *
     * @param notiTp the value for tb_user_noti.NOTI_TP
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    public void setNotiTp(String notiTp) {
        this.notiTp = notiTp == null ? null : notiTp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_noti.OPT_TP
     *
     * @return the value of tb_user_noti.OPT_TP
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    public String getOptTp() {
        return optTp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_noti.OPT_TP
     *
     * @param optTp the value for tb_user_noti.OPT_TP
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    public void setOptTp(String optTp) {
        this.optTp = optTp == null ? null : optTp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_noti.USED
     *
     * @return the value of tb_user_noti.USED
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    public Boolean getUsed() {
        return used;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_noti.USED
     *
     * @param used the value for tb_user_noti.USED
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    public void setUsed(Boolean used) {
        this.used = used;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_noti.CREATED
     *
     * @return the value of tb_user_noti.CREATED
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_noti.CREATED
     *
     * @param created the value for tb_user_noti.CREATED
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_noti.UPDATED
     *
     * @return the value of tb_user_noti.UPDATED
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    public Date getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_noti.UPDATED
     *
     * @param updated the value for tb_user_noti.UPDATED
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
}