package com.jc.pico.bean;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.Date;

@JsonIgnoreProperties(ignoreUnknown = true)
public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.ID
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.PLATFORM_ID
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    private Long platformId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.TYPE
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.STATUS
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.GRP_CD
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    private String grpCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.MEM_CD
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    private Integer memCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.USER_ROLE
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    private String userRole;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.ADM_USE
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    private Byte admUse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.BARCODE
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    private String barcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.USERNAME
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.PASSWORD
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.NAME
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.FIRST_NAME
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    private String firstName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.MID_NAME
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    private String midName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.LAST_NAME
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    private String lastName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.EMAIL
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.MB_COUNTRY_CD
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    private String mbCountryCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.MB
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    private String mb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.MB_BK
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    private String mbBk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.TEL_COUNTRY_CD
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    private String telCountryCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.TEL
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.FAX_COUNTRY_CD
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    private String faxCountryCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.FAX
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    private String fax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.GENDER
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.BIRTHDAY
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    private String birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.COUNTRY
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    private String country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.REGION
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    private String region;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.CITY
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.ADDR1
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    private String addr1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.ADDR2
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    private String addr2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.ZIP
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    private String zip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.LAST_LOGIN
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    private Date lastLogin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.LOGIN_TRY_TM
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    private Date loginTryTm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.LOGIN_FAIL_CNT
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    private Byte loginFailCnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.IS_MB_AUTH
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    private Boolean isMbAuth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.MB_AUTH_TM
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    private Date mbAuthTm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.IS_EMAIL_AUTH
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    private Boolean isEmailAuth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.EMAIL_AUTH_TM
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    private Date emailAuthTm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.IS_SVC_SMS
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    private Boolean isSvcSms;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.IS_SVC_PUSH
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    private Boolean isSvcPush;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.IS_SVC_BLUETOOTH
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    private Boolean isSvcBluetooth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.LAST_BEACON_PUSH
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    private Date lastBeaconPush;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.SEC_TOKEN
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    private String secToken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.CREATED
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.UPDATED
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    private Date updated;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.ID
     *
     * @return the value of tb_user.ID
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.ID
     *
     * @param id the value for tb_user.ID
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.PLATFORM_ID
     *
     * @return the value of tb_user.PLATFORM_ID
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    public Long getPlatformId() {
        return platformId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.PLATFORM_ID
     *
     * @param platformId the value for tb_user.PLATFORM_ID
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    public void setPlatformId(Long platformId) {
        this.platformId = platformId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.TYPE
     *
     * @return the value of tb_user.TYPE
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.TYPE
     *
     * @param type the value for tb_user.TYPE
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.STATUS
     *
     * @return the value of tb_user.STATUS
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.STATUS
     *
     * @param status the value for tb_user.STATUS
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.GRP_CD
     *
     * @return the value of tb_user.GRP_CD
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    public String getGrpCd() {
        return grpCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.GRP_CD
     *
     * @param grpCd the value for tb_user.GRP_CD
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    public void setGrpCd(String grpCd) {
        this.grpCd = grpCd == null ? null : grpCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.MEM_CD
     *
     * @return the value of tb_user.MEM_CD
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    public Integer getMemCd() {
        return memCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.MEM_CD
     *
     * @param memCd the value for tb_user.MEM_CD
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    public void setMemCd(Integer memCd) {
        this.memCd = memCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.USER_ROLE
     *
     * @return the value of tb_user.USER_ROLE
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    public String getUserRole() {
        return userRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.USER_ROLE
     *
     * @param userRole the value for tb_user.USER_ROLE
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    public void setUserRole(String userRole) {
        this.userRole = userRole == null ? null : userRole.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.ADM_USE
     *
     * @return the value of tb_user.ADM_USE
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    public Byte getAdmUse() {
        return admUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.ADM_USE
     *
     * @param admUse the value for tb_user.ADM_USE
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    public void setAdmUse(Byte admUse) {
        this.admUse = admUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.BARCODE
     *
     * @return the value of tb_user.BARCODE
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    public String getBarcode() {
        return barcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.BARCODE
     *
     * @param barcode the value for tb_user.BARCODE
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    public void setBarcode(String barcode) {
        this.barcode = barcode == null ? null : barcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.USERNAME
     *
     * @return the value of tb_user.USERNAME
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.USERNAME
     *
     * @param username the value for tb_user.USERNAME
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.PASSWORD
     *
     * @return the value of tb_user.PASSWORD
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.PASSWORD
     *
     * @param password the value for tb_user.PASSWORD
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.NAME
     *
     * @return the value of tb_user.NAME
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.NAME
     *
     * @param name the value for tb_user.NAME
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.FIRST_NAME
     *
     * @return the value of tb_user.FIRST_NAME
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.FIRST_NAME
     *
     * @param firstName the value for tb_user.FIRST_NAME
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName == null ? null : firstName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.MID_NAME
     *
     * @return the value of tb_user.MID_NAME
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    public String getMidName() {
        return midName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.MID_NAME
     *
     * @param midName the value for tb_user.MID_NAME
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    public void setMidName(String midName) {
        this.midName = midName == null ? null : midName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.LAST_NAME
     *
     * @return the value of tb_user.LAST_NAME
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.LAST_NAME
     *
     * @param lastName the value for tb_user.LAST_NAME
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    public void setLastName(String lastName) {
        this.lastName = lastName == null ? null : lastName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.EMAIL
     *
     * @return the value of tb_user.EMAIL
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.EMAIL
     *
     * @param email the value for tb_user.EMAIL
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.MB_COUNTRY_CD
     *
     * @return the value of tb_user.MB_COUNTRY_CD
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    public String getMbCountryCd() {
        return mbCountryCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.MB_COUNTRY_CD
     *
     * @param mbCountryCd the value for tb_user.MB_COUNTRY_CD
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    public void setMbCountryCd(String mbCountryCd) {
        this.mbCountryCd = mbCountryCd == null ? null : mbCountryCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.MB
     *
     * @return the value of tb_user.MB
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    public String getMb() {
        return mb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.MB
     *
     * @param mb the value for tb_user.MB
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    public void setMb(String mb) {
        this.mb = mb == null ? null : mb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.MB_BK
     *
     * @return the value of tb_user.MB_BK
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    public String getMbBk() {
        return mbBk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.MB_BK
     *
     * @param mbBk the value for tb_user.MB_BK
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    public void setMbBk(String mbBk) {
        this.mbBk = mbBk == null ? null : mbBk.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.TEL_COUNTRY_CD
     *
     * @return the value of tb_user.TEL_COUNTRY_CD
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    public String getTelCountryCd() {
        return telCountryCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.TEL_COUNTRY_CD
     *
     * @param telCountryCd the value for tb_user.TEL_COUNTRY_CD
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    public void setTelCountryCd(String telCountryCd) {
        this.telCountryCd = telCountryCd == null ? null : telCountryCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.TEL
     *
     * @return the value of tb_user.TEL
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.TEL
     *
     * @param tel the value for tb_user.TEL
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.FAX_COUNTRY_CD
     *
     * @return the value of tb_user.FAX_COUNTRY_CD
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    public String getFaxCountryCd() {
        return faxCountryCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.FAX_COUNTRY_CD
     *
     * @param faxCountryCd the value for tb_user.FAX_COUNTRY_CD
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    public void setFaxCountryCd(String faxCountryCd) {
        this.faxCountryCd = faxCountryCd == null ? null : faxCountryCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.FAX
     *
     * @return the value of tb_user.FAX
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.FAX
     *
     * @param fax the value for tb_user.FAX
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    public void setFax(String fax) {
        this.fax = fax == null ? null : fax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.GENDER
     *
     * @return the value of tb_user.GENDER
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.GENDER
     *
     * @param gender the value for tb_user.GENDER
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.BIRTHDAY
     *
     * @return the value of tb_user.BIRTHDAY
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.BIRTHDAY
     *
     * @param birthday the value for tb_user.BIRTHDAY
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday == null ? null : birthday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.COUNTRY
     *
     * @return the value of tb_user.COUNTRY
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.COUNTRY
     *
     * @param country the value for tb_user.COUNTRY
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.REGION
     *
     * @return the value of tb_user.REGION
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    public String getRegion() {
        return region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.REGION
     *
     * @param region the value for tb_user.REGION
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    public void setRegion(String region) {
        this.region = region == null ? null : region.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.CITY
     *
     * @return the value of tb_user.CITY
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.CITY
     *
     * @param city the value for tb_user.CITY
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.ADDR1
     *
     * @return the value of tb_user.ADDR1
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    public String getAddr1() {
        return addr1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.ADDR1
     *
     * @param addr1 the value for tb_user.ADDR1
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    public void setAddr1(String addr1) {
        this.addr1 = addr1 == null ? null : addr1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.ADDR2
     *
     * @return the value of tb_user.ADDR2
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    public String getAddr2() {
        return addr2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.ADDR2
     *
     * @param addr2 the value for tb_user.ADDR2
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    public void setAddr2(String addr2) {
        this.addr2 = addr2 == null ? null : addr2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.ZIP
     *
     * @return the value of tb_user.ZIP
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    public String getZip() {
        return zip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.ZIP
     *
     * @param zip the value for tb_user.ZIP
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    public void setZip(String zip) {
        this.zip = zip == null ? null : zip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.LAST_LOGIN
     *
     * @return the value of tb_user.LAST_LOGIN
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    public Date getLastLogin() {
        return lastLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.LAST_LOGIN
     *
     * @param lastLogin the value for tb_user.LAST_LOGIN
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    public void setLastLogin(Date lastLogin) {
        this.lastLogin = lastLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.LOGIN_TRY_TM
     *
     * @return the value of tb_user.LOGIN_TRY_TM
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    public Date getLoginTryTm() {
        return loginTryTm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.LOGIN_TRY_TM
     *
     * @param loginTryTm the value for tb_user.LOGIN_TRY_TM
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    public void setLoginTryTm(Date loginTryTm) {
        this.loginTryTm = loginTryTm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.LOGIN_FAIL_CNT
     *
     * @return the value of tb_user.LOGIN_FAIL_CNT
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    public Byte getLoginFailCnt() {
        return loginFailCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.LOGIN_FAIL_CNT
     *
     * @param loginFailCnt the value for tb_user.LOGIN_FAIL_CNT
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    public void setLoginFailCnt(Byte loginFailCnt) {
        this.loginFailCnt = loginFailCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.IS_MB_AUTH
     *
     * @return the value of tb_user.IS_MB_AUTH
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    public Boolean getIsMbAuth() {
        return isMbAuth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.IS_MB_AUTH
     *
     * @param isMbAuth the value for tb_user.IS_MB_AUTH
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    public void setIsMbAuth(Boolean isMbAuth) {
        this.isMbAuth = isMbAuth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.MB_AUTH_TM
     *
     * @return the value of tb_user.MB_AUTH_TM
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    public Date getMbAuthTm() {
        return mbAuthTm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.MB_AUTH_TM
     *
     * @param mbAuthTm the value for tb_user.MB_AUTH_TM
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    public void setMbAuthTm(Date mbAuthTm) {
        this.mbAuthTm = mbAuthTm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.IS_EMAIL_AUTH
     *
     * @return the value of tb_user.IS_EMAIL_AUTH
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    public Boolean getIsEmailAuth() {
        return isEmailAuth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.IS_EMAIL_AUTH
     *
     * @param isEmailAuth the value for tb_user.IS_EMAIL_AUTH
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    public void setIsEmailAuth(Boolean isEmailAuth) {
        this.isEmailAuth = isEmailAuth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.EMAIL_AUTH_TM
     *
     * @return the value of tb_user.EMAIL_AUTH_TM
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    public Date getEmailAuthTm() {
        return emailAuthTm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.EMAIL_AUTH_TM
     *
     * @param emailAuthTm the value for tb_user.EMAIL_AUTH_TM
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    public void setEmailAuthTm(Date emailAuthTm) {
        this.emailAuthTm = emailAuthTm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.IS_SVC_SMS
     *
     * @return the value of tb_user.IS_SVC_SMS
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    public Boolean getIsSvcSms() {
        return isSvcSms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.IS_SVC_SMS
     *
     * @param isSvcSms the value for tb_user.IS_SVC_SMS
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    public void setIsSvcSms(Boolean isSvcSms) {
        this.isSvcSms = isSvcSms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.IS_SVC_PUSH
     *
     * @return the value of tb_user.IS_SVC_PUSH
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    public Boolean getIsSvcPush() {
        return isSvcPush;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.IS_SVC_PUSH
     *
     * @param isSvcPush the value for tb_user.IS_SVC_PUSH
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    public void setIsSvcPush(Boolean isSvcPush) {
        this.isSvcPush = isSvcPush;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.IS_SVC_BLUETOOTH
     *
     * @return the value of tb_user.IS_SVC_BLUETOOTH
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    public Boolean getIsSvcBluetooth() {
        return isSvcBluetooth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.IS_SVC_BLUETOOTH
     *
     * @param isSvcBluetooth the value for tb_user.IS_SVC_BLUETOOTH
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    public void setIsSvcBluetooth(Boolean isSvcBluetooth) {
        this.isSvcBluetooth = isSvcBluetooth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.LAST_BEACON_PUSH
     *
     * @return the value of tb_user.LAST_BEACON_PUSH
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    public Date getLastBeaconPush() {
        return lastBeaconPush;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.LAST_BEACON_PUSH
     *
     * @param lastBeaconPush the value for tb_user.LAST_BEACON_PUSH
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    public void setLastBeaconPush(Date lastBeaconPush) {
        this.lastBeaconPush = lastBeaconPush;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.SEC_TOKEN
     *
     * @return the value of tb_user.SEC_TOKEN
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    public String getSecToken() {
        return secToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.SEC_TOKEN
     *
     * @param secToken the value for tb_user.SEC_TOKEN
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    public void setSecToken(String secToken) {
        this.secToken = secToken == null ? null : secToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.CREATED
     *
     * @return the value of tb_user.CREATED
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.CREATED
     *
     * @param created the value for tb_user.CREATED
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.UPDATED
     *
     * @return the value of tb_user.UPDATED
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    public Date getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.UPDATED
     *
     * @param updated the value for tb_user.UPDATED
     *
     * @mbggenerated Mon Sep 19 11:40:46 KST 2016
     */
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
}