package com.jc.pico.bean;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.Date;

@JsonIgnoreProperties(ignoreUnknown = true)
public class UserOauth {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_oauth.ID
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_oauth.USER_ID
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_oauth.PROVIDER
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    private String provider;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_oauth.ACCESS_TOKEN
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    private String accessToken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_oauth.EXPIRE_IN
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    private Integer expireIn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_oauth.REFRESH_TOKEN
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    private String refreshToken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_oauth.CREATED
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_oauth.UPDATED
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    private Date updated;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_oauth.ID
     *
     * @return the value of tb_user_oauth.ID
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_oauth.ID
     *
     * @param id the value for tb_user_oauth.ID
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_oauth.USER_ID
     *
     * @return the value of tb_user_oauth.USER_ID
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_oauth.USER_ID
     *
     * @param userId the value for tb_user_oauth.USER_ID
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_oauth.PROVIDER
     *
     * @return the value of tb_user_oauth.PROVIDER
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    public String getProvider() {
        return provider;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_oauth.PROVIDER
     *
     * @param provider the value for tb_user_oauth.PROVIDER
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    public void setProvider(String provider) {
        this.provider = provider == null ? null : provider.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_oauth.ACCESS_TOKEN
     *
     * @return the value of tb_user_oauth.ACCESS_TOKEN
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    public String getAccessToken() {
        return accessToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_oauth.ACCESS_TOKEN
     *
     * @param accessToken the value for tb_user_oauth.ACCESS_TOKEN
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    public void setAccessToken(String accessToken) {
        this.accessToken = accessToken == null ? null : accessToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_oauth.EXPIRE_IN
     *
     * @return the value of tb_user_oauth.EXPIRE_IN
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    public Integer getExpireIn() {
        return expireIn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_oauth.EXPIRE_IN
     *
     * @param expireIn the value for tb_user_oauth.EXPIRE_IN
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    public void setExpireIn(Integer expireIn) {
        this.expireIn = expireIn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_oauth.REFRESH_TOKEN
     *
     * @return the value of tb_user_oauth.REFRESH_TOKEN
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    public String getRefreshToken() {
        return refreshToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_oauth.REFRESH_TOKEN
     *
     * @param refreshToken the value for tb_user_oauth.REFRESH_TOKEN
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    public void setRefreshToken(String refreshToken) {
        this.refreshToken = refreshToken == null ? null : refreshToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_oauth.CREATED
     *
     * @return the value of tb_user_oauth.CREATED
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_oauth.CREATED
     *
     * @param created the value for tb_user_oauth.CREATED
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_oauth.UPDATED
     *
     * @return the value of tb_user_oauth.UPDATED
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    public Date getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_oauth.UPDATED
     *
     * @param updated the value for tb_user_oauth.UPDATED
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
}