package com.jc.pico.bean;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

@JsonIgnoreProperties(ignoreUnknown = true)
public class Zipcode {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_zipcode.AREA_CD
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    private String areaCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_zipcode.AREA_NO
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    private String areaNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_zipcode.ZIP
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    private String zip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_zipcode.CD_1
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    private String cd1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_zipcode.CD_2
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    private String cd2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_zipcode.CD_3
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    private String cd3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_zipcode.CD_4
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    private String cd4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_zipcode.CD_5
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    private String cd5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_zipcode.CD_6
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    private String cd6;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_zipcode.AREA_CD
     *
     * @return the value of tb_zipcode.AREA_CD
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    public String getAreaCd() {
        return areaCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_zipcode.AREA_CD
     *
     * @param areaCd the value for tb_zipcode.AREA_CD
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    public void setAreaCd(String areaCd) {
        this.areaCd = areaCd == null ? null : areaCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_zipcode.AREA_NO
     *
     * @return the value of tb_zipcode.AREA_NO
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    public String getAreaNo() {
        return areaNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_zipcode.AREA_NO
     *
     * @param areaNo the value for tb_zipcode.AREA_NO
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    public void setAreaNo(String areaNo) {
        this.areaNo = areaNo == null ? null : areaNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_zipcode.ZIP
     *
     * @return the value of tb_zipcode.ZIP
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    public String getZip() {
        return zip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_zipcode.ZIP
     *
     * @param zip the value for tb_zipcode.ZIP
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    public void setZip(String zip) {
        this.zip = zip == null ? null : zip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_zipcode.CD_1
     *
     * @return the value of tb_zipcode.CD_1
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    public String getCd1() {
        return cd1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_zipcode.CD_1
     *
     * @param cd1 the value for tb_zipcode.CD_1
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    public void setCd1(String cd1) {
        this.cd1 = cd1 == null ? null : cd1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_zipcode.CD_2
     *
     * @return the value of tb_zipcode.CD_2
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    public String getCd2() {
        return cd2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_zipcode.CD_2
     *
     * @param cd2 the value for tb_zipcode.CD_2
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    public void setCd2(String cd2) {
        this.cd2 = cd2 == null ? null : cd2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_zipcode.CD_3
     *
     * @return the value of tb_zipcode.CD_3
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    public String getCd3() {
        return cd3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_zipcode.CD_3
     *
     * @param cd3 the value for tb_zipcode.CD_3
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    public void setCd3(String cd3) {
        this.cd3 = cd3 == null ? null : cd3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_zipcode.CD_4
     *
     * @return the value of tb_zipcode.CD_4
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    public String getCd4() {
        return cd4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_zipcode.CD_4
     *
     * @param cd4 the value for tb_zipcode.CD_4
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    public void setCd4(String cd4) {
        this.cd4 = cd4 == null ? null : cd4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_zipcode.CD_5
     *
     * @return the value of tb_zipcode.CD_5
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    public String getCd5() {
        return cd5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_zipcode.CD_5
     *
     * @param cd5 the value for tb_zipcode.CD_5
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    public void setCd5(String cd5) {
        this.cd5 = cd5 == null ? null : cd5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_zipcode.CD_6
     *
     * @return the value of tb_zipcode.CD_6
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    public String getCd6() {
        return cd6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_zipcode.CD_6
     *
     * @param cd6 the value for tb_zipcode.CD_6
     *
     * @mbggenerated Thu Aug 04 11:39:46 KST 2016
     */
    public void setCd6(String cd6) {
        this.cd6 = cd6 == null ? null : cd6.trim();
    }
}