package com.jc.pico.mapper;

import com.jc.pico.bean.BaseMcode;
import com.jc.pico.bean.BaseMcodeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface BaseMcodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_BASE_MCODE
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    int countByExample(BaseMcodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_BASE_MCODE
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    int deleteByExample(BaseMcodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_BASE_MCODE
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    int deleteByPrimaryKey(String mainCd);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_BASE_MCODE
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    int insert(BaseMcode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_BASE_MCODE
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    int insertSelective(BaseMcode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_BASE_MCODE
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    List<BaseMcode> selectByExampleWithRowbounds(BaseMcodeExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_BASE_MCODE
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    List<BaseMcode> selectByExample(BaseMcodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_BASE_MCODE
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    BaseMcode selectByPrimaryKey(String mainCd);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_BASE_MCODE
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    int updateByExampleSelective(@Param("record") BaseMcode record, @Param("example") BaseMcodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_BASE_MCODE
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    int updateByExample(@Param("record") BaseMcode record, @Param("example") BaseMcodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_BASE_MCODE
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    int updateByPrimaryKeySelective(BaseMcode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_BASE_MCODE
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    int updateByPrimaryKey(BaseMcode record);
}