package com.jc.pico.mapper;

import com.jc.pico.bean.SvcCouponPromotion;
import com.jc.pico.bean.SvcCouponPromotionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SvcCouponPromotionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SVC_COUPON_PROMOTION
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    int countByExample(SvcCouponPromotionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SVC_COUPON_PROMOTION
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    int deleteByExample(SvcCouponPromotionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SVC_COUPON_PROMOTION
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SVC_COUPON_PROMOTION
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    int insert(SvcCouponPromotion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SVC_COUPON_PROMOTION
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    int insertSelective(SvcCouponPromotion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SVC_COUPON_PROMOTION
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    List<SvcCouponPromotion> selectByExampleWithRowbounds(SvcCouponPromotionExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SVC_COUPON_PROMOTION
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    List<SvcCouponPromotion> selectByExample(SvcCouponPromotionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SVC_COUPON_PROMOTION
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    SvcCouponPromotion selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SVC_COUPON_PROMOTION
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    int updateByExampleSelective(@Param("record") SvcCouponPromotion record, @Param("example") SvcCouponPromotionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SVC_COUPON_PROMOTION
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    int updateByExample(@Param("record") SvcCouponPromotion record, @Param("example") SvcCouponPromotionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SVC_COUPON_PROMOTION
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    int updateByPrimaryKeySelective(SvcCouponPromotion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SVC_COUPON_PROMOTION
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    int updateByPrimaryKey(SvcCouponPromotion record);
}