package com.jc.pico.mapper;

import com.jc.pico.bean.SvcItemOptDtl;
import com.jc.pico.bean.SvcItemOptDtlExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SvcItemOptDtlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_item_opt_dtl
     *
     * @mbggenerated Tue Sep 27 09:42:36 KST 2016
     */
    int countByExample(SvcItemOptDtlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_item_opt_dtl
     *
     * @mbggenerated Tue Sep 27 09:42:36 KST 2016
     */
    int deleteByExample(SvcItemOptDtlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_item_opt_dtl
     *
     * @mbggenerated Tue Sep 27 09:42:36 KST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_item_opt_dtl
     *
     * @mbggenerated Tue Sep 27 09:42:36 KST 2016
     */
    int insert(SvcItemOptDtl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_item_opt_dtl
     *
     * @mbggenerated Tue Sep 27 09:42:36 KST 2016
     */
    int insertSelective(SvcItemOptDtl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_item_opt_dtl
     *
     * @mbggenerated Tue Sep 27 09:42:36 KST 2016
     */
    List<SvcItemOptDtl> selectByExampleWithRowbounds(SvcItemOptDtlExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_item_opt_dtl
     *
     * @mbggenerated Tue Sep 27 09:42:36 KST 2016
     */
    List<SvcItemOptDtl> selectByExample(SvcItemOptDtlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_item_opt_dtl
     *
     * @mbggenerated Tue Sep 27 09:42:36 KST 2016
     */
    SvcItemOptDtl selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_item_opt_dtl
     *
     * @mbggenerated Tue Sep 27 09:42:36 KST 2016
     */
    int updateByExampleSelective(@Param("record") SvcItemOptDtl record, @Param("example") SvcItemOptDtlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_item_opt_dtl
     *
     * @mbggenerated Tue Sep 27 09:42:36 KST 2016
     */
    int updateByExample(@Param("record") SvcItemOptDtl record, @Param("example") SvcItemOptDtlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_item_opt_dtl
     *
     * @mbggenerated Tue Sep 27 09:42:36 KST 2016
     */
    int updateByPrimaryKeySelective(SvcItemOptDtl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_item_opt_dtl
     *
     * @mbggenerated Tue Sep 27 09:42:36 KST 2016
     */
    int updateByPrimaryKey(SvcItemOptDtl record);
}