package com.jc.pico.mapper;

import com.jc.pico.bean.SvcMessageTemplate;
import com.jc.pico.bean.SvcMessageTemplateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SvcMessageTemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SVC_MESSAGE_TEMPLATE
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    int countByExample(SvcMessageTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SVC_MESSAGE_TEMPLATE
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    int deleteByExample(SvcMessageTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SVC_MESSAGE_TEMPLATE
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SVC_MESSAGE_TEMPLATE
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    int insert(SvcMessageTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SVC_MESSAGE_TEMPLATE
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    int insertSelective(SvcMessageTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SVC_MESSAGE_TEMPLATE
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    List<SvcMessageTemplate> selectByExampleWithRowbounds(SvcMessageTemplateExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SVC_MESSAGE_TEMPLATE
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    List<SvcMessageTemplate> selectByExample(SvcMessageTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SVC_MESSAGE_TEMPLATE
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    SvcMessageTemplate selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SVC_MESSAGE_TEMPLATE
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    int updateByExampleSelective(@Param("record") SvcMessageTemplate record, @Param("example") SvcMessageTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SVC_MESSAGE_TEMPLATE
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    int updateByExample(@Param("record") SvcMessageTemplate record, @Param("example") SvcMessageTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SVC_MESSAGE_TEMPLATE
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    int updateByPrimaryKeySelective(SvcMessageTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SVC_MESSAGE_TEMPLATE
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    int updateByPrimaryKey(SvcMessageTemplate record);
}