package com.jc.pico.mapper;

import com.jc.pico.bean.SvcMailAccount;
import com.jc.pico.bean.SvcMailAccountExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SvcMailAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SVC_MAIL_ACCOUNT
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    int countByExample(SvcMailAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SVC_MAIL_ACCOUNT
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    int deleteByExample(SvcMailAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SVC_MAIL_ACCOUNT
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SVC_MAIL_ACCOUNT
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    int insert(SvcMailAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SVC_MAIL_ACCOUNT
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    int insertSelective(SvcMailAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SVC_MAIL_ACCOUNT
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    List<SvcMailAccount> selectByExampleWithRowbounds(SvcMailAccountExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SVC_MAIL_ACCOUNT
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    List<SvcMailAccount> selectByExample(SvcMailAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SVC_MAIL_ACCOUNT
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    SvcMailAccount selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SVC_MAIL_ACCOUNT
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    int updateByExampleSelective(@Param("record") SvcMailAccount record, @Param("example") SvcMailAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SVC_MAIL_ACCOUNT
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    int updateByExample(@Param("record") SvcMailAccount record, @Param("example") SvcMailAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SVC_MAIL_ACCOUNT
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    int updateByPrimaryKeySelective(SvcMailAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SVC_MAIL_ACCOUNT
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    int updateByPrimaryKey(SvcMailAccount record);
}