package com.jc.pico.mapper;

import com.jc.pico.bean.SvcOrder;
import com.jc.pico.bean.SvcOrderExample;
import com.jc.pico.utils.bean.SingleMap;

import java.util.HashMap;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SvcOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_order
     *
     * @mbggenerated Fri Oct 14 11:41:42 KST 2016
     */
    int countByExample(SvcOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_order
     *
     * @mbggenerated Fri Oct 14 11:41:42 KST 2016
     */
    int deleteByExample(SvcOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_order
     *
     * @mbggenerated Fri Oct 14 11:41:42 KST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_order
     *
     * @mbggenerated Fri Oct 14 11:41:42 KST 2016
     */
    int insert(SvcOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_order
     *
     * @mbggenerated Fri Oct 14 11:41:42 KST 2016
     */
    int insertSelective(SvcOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_order
     *
     * @mbggenerated Fri Oct 14 11:41:42 KST 2016
     */
    List<SvcOrder> selectByExampleWithRowbounds(SvcOrderExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_order
     *
     * @mbggenerated Fri Oct 14 11:41:42 KST 2016
     */
    List<SvcOrder> selectByExample(SvcOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_order
     *
     * @mbggenerated Fri Oct 14 11:41:42 KST 2016
     */
    SvcOrder selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_order
     *
     * @mbggenerated Fri Oct 14 11:41:42 KST 2016
     */
    int updateByExampleSelective(@Param("record") SvcOrder record, @Param("example") SvcOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_order
     *
     * @mbggenerated Fri Oct 14 11:41:42 KST 2016
     */
    int updateByExample(@Param("record") SvcOrder record, @Param("example") SvcOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_order
     *
     * @mbggenerated Fri Oct 14 11:41:42 KST 2016
     */
    int updateByPrimaryKeySelective(SvcOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_order
     *
     * @mbggenerated Fri Oct 14 11:41:42 KST 2016
     */
    int updateByPrimaryKey(SvcOrder record);
    
    
    
    /**
     * 주문 취소(주문)
     *   주문승인 : ORDER_ST(607002)    -->   주문 취소 : ORDER_ST(607003)
     * 추가 : 
     *   
     * @param order
     * @return
     */
    int updateByOrderCancel(HashMap order);
    
    /**
     * 주문 취소(매출)
     *   주문승인 : ORDER_ST(607005)  --> ORDER_ST(607003) 
     * 추가 : 
     *   
     * @param order
     * @return
     */
    int updateBySalesCancel(HashMap sales);

	void setKioskAccess(SingleMap param);
	
}