package com.jc.pico.mapper;

import com.jc.pico.bean.SvcOrderItemHistory;
import com.jc.pico.bean.SvcOrderItemHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SvcOrderItemHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_order_item_history
     *
     * @mbggenerated Thu Oct 27 10:45:47 KST 2016
     */
    int countByExample(SvcOrderItemHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_order_item_history
     *
     * @mbggenerated Thu Oct 27 10:45:47 KST 2016
     */
    int deleteByExample(SvcOrderItemHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_order_item_history
     *
     * @mbggenerated Thu Oct 27 10:45:47 KST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_order_item_history
     *
     * @mbggenerated Thu Oct 27 10:45:47 KST 2016
     */
    int insert(SvcOrderItemHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_order_item_history
     *
     * @mbggenerated Thu Oct 27 10:45:47 KST 2016
     */
    int insertSelective(SvcOrderItemHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_order_item_history
     *
     * @mbggenerated Thu Oct 27 10:45:47 KST 2016
     */
    List<SvcOrderItemHistory> selectByExampleWithRowbounds(SvcOrderItemHistoryExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_order_item_history
     *
     * @mbggenerated Thu Oct 27 10:45:47 KST 2016
     */
    List<SvcOrderItemHistory> selectByExample(SvcOrderItemHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_order_item_history
     *
     * @mbggenerated Thu Oct 27 10:45:47 KST 2016
     */
    SvcOrderItemHistory selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_order_item_history
     *
     * @mbggenerated Thu Oct 27 10:45:47 KST 2016
     */
    int updateByExampleSelective(@Param("record") SvcOrderItemHistory record, @Param("example") SvcOrderItemHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_order_item_history
     *
     * @mbggenerated Thu Oct 27 10:45:47 KST 2016
     */
    int updateByExample(@Param("record") SvcOrderItemHistory record, @Param("example") SvcOrderItemHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_order_item_history
     *
     * @mbggenerated Thu Oct 27 10:45:47 KST 2016
     */
    int updateByPrimaryKeySelective(SvcOrderItemHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_order_item_history
     *
     * @mbggenerated Thu Oct 27 10:45:47 KST 2016
     */
    int updateByPrimaryKey(SvcOrderItemHistory record);
}