package com.jc.pico.mapper;

import com.jc.pico.bean.SvcOrderPay;
import com.jc.pico.bean.SvcOrderPayExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SvcOrderPayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_order_pay
     *
     * @mbggenerated Fri Jan 06 17:22:42 KST 2017
     */
    int countByExample(SvcOrderPayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_order_pay
     *
     * @mbggenerated Fri Jan 06 17:22:42 KST 2017
     */
    int deleteByExample(SvcOrderPayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_order_pay
     *
     * @mbggenerated Fri Jan 06 17:22:42 KST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_order_pay
     *
     * @mbggenerated Fri Jan 06 17:22:42 KST 2017
     */
    int insert(SvcOrderPay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_order_pay
     *
     * @mbggenerated Fri Jan 06 17:22:42 KST 2017
     */
    int insertSelective(SvcOrderPay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_order_pay
     *
     * @mbggenerated Fri Jan 06 17:22:42 KST 2017
     */
    List<SvcOrderPay> selectByExampleWithRowbounds(SvcOrderPayExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_order_pay
     *
     * @mbggenerated Fri Jan 06 17:22:42 KST 2017
     */
    List<SvcOrderPay> selectByExample(SvcOrderPayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_order_pay
     *
     * @mbggenerated Fri Jan 06 17:22:42 KST 2017
     */
    SvcOrderPay selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_order_pay
     *
     * @mbggenerated Fri Jan 06 17:22:42 KST 2017
     */
    int updateByExampleSelective(@Param("record") SvcOrderPay record, @Param("example") SvcOrderPayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_order_pay
     *
     * @mbggenerated Fri Jan 06 17:22:42 KST 2017
     */
    int updateByExample(@Param("record") SvcOrderPay record, @Param("example") SvcOrderPayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_order_pay
     *
     * @mbggenerated Fri Jan 06 17:22:42 KST 2017
     */
    int updateByPrimaryKeySelective(SvcOrderPay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_order_pay
     *
     * @mbggenerated Fri Jan 06 17:22:42 KST 2017
     */
    int updateByPrimaryKey(SvcOrderPay record);
    
    
    // 추가 : 
    SvcOrderPay selectByOrderId(Long orderId);
    
   
}