package com.jc.pico.mapper;

import com.jc.pico.bean.SvcReserve;
import com.jc.pico.bean.SvcReserveExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface SvcReserveMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SVC_RESERVE
	 * @mbggenerated  Fri May 20 15:37:02 KST 2016
	 */
	int countByExample(SvcReserveExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SVC_RESERVE
	 * @mbggenerated  Fri May 20 15:37:02 KST 2016
	 */
	int deleteByExample(SvcReserveExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SVC_RESERVE
	 * @mbggenerated  Fri May 20 15:37:02 KST 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SVC_RESERVE
	 * @mbggenerated  Fri May 20 15:37:02 KST 2016
	 */
	int insert(SvcReserve record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SVC_RESERVE
	 * @mbggenerated  Fri May 20 15:37:02 KST 2016
	 */
	int insertSelective(SvcReserve record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SVC_RESERVE
	 * @mbggenerated  Fri May 20 15:37:02 KST 2016
	 */
	List<SvcReserve> selectByExampleWithRowbounds(SvcReserveExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SVC_RESERVE
	 * @mbggenerated  Fri May 20 15:37:02 KST 2016
	 */
	List<SvcReserve> selectByExample(SvcReserveExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SVC_RESERVE
	 * @mbggenerated  Fri May 20 15:37:02 KST 2016
	 */
	SvcReserve selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SVC_RESERVE
	 * @mbggenerated  Fri May 20 15:37:02 KST 2016
	 */
	int updateByExampleSelective(@Param("record") SvcReserve record, @Param("example") SvcReserveExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SVC_RESERVE
	 * @mbggenerated  Fri May 20 15:37:02 KST 2016
	 */
	int updateByExample(@Param("record") SvcReserve record, @Param("example") SvcReserveExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SVC_RESERVE
	 * @mbggenerated  Fri May 20 15:37:02 KST 2016
	 */
	int updateByPrimaryKeySelective(SvcReserve record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SVC_RESERVE
	 * @mbggenerated  Fri May 20 15:37:02 KST 2016
	 */
	int updateByPrimaryKey(SvcReserve record);
}