package com.jc.pico.mapper;

import com.jc.pico.bean.SvcSupplyCompany;
import com.jc.pico.bean.SvcSupplyCompanyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SvcSupplyCompanyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_supply_company
     *
     * @mbggenerated Mon Dec 05 10:10:11 KST 2016
     */
    int countByExample(SvcSupplyCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_supply_company
     *
     * @mbggenerated Mon Dec 05 10:10:11 KST 2016
     */
    int deleteByExample(SvcSupplyCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_supply_company
     *
     * @mbggenerated Mon Dec 05 10:10:11 KST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_supply_company
     *
     * @mbggenerated Mon Dec 05 10:10:11 KST 2016
     */
    int insert(SvcSupplyCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_supply_company
     *
     * @mbggenerated Mon Dec 05 10:10:11 KST 2016
     */
    int insertSelective(SvcSupplyCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_supply_company
     *
     * @mbggenerated Mon Dec 05 10:10:11 KST 2016
     */
    List<SvcSupplyCompany> selectByExampleWithRowbounds(SvcSupplyCompanyExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_supply_company
     *
     * @mbggenerated Mon Dec 05 10:10:11 KST 2016
     */
    List<SvcSupplyCompany> selectByExample(SvcSupplyCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_supply_company
     *
     * @mbggenerated Mon Dec 05 10:10:11 KST 2016
     */
    SvcSupplyCompany selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_supply_company
     *
     * @mbggenerated Mon Dec 05 10:10:11 KST 2016
     */
    int updateByExampleSelective(@Param("record") SvcSupplyCompany record, @Param("example") SvcSupplyCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_supply_company
     *
     * @mbggenerated Mon Dec 05 10:10:11 KST 2016
     */
    int updateByExample(@Param("record") SvcSupplyCompany record, @Param("example") SvcSupplyCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_supply_company
     *
     * @mbggenerated Mon Dec 05 10:10:11 KST 2016
     */
    int updateByPrimaryKeySelective(SvcSupplyCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_supply_company
     *
     * @mbggenerated Mon Dec 05 10:10:11 KST 2016
     */
    int updateByPrimaryKey(SvcSupplyCompany record);
}