package com.jc.pico.mapper;

import com.jc.pico.bean.SvcStampLog;
import com.jc.pico.bean.SvcStampLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SvcStampLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SVC_STAMP_LOG
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    int countByExample(SvcStampLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SVC_STAMP_LOG
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    int deleteByExample(SvcStampLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SVC_STAMP_LOG
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SVC_STAMP_LOG
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    int insert(SvcStampLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SVC_STAMP_LOG
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    int insertSelective(SvcStampLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SVC_STAMP_LOG
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    List<SvcStampLog> selectByExampleWithRowbounds(SvcStampLogExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SVC_STAMP_LOG
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    List<SvcStampLog> selectByExample(SvcStampLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SVC_STAMP_LOG
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    SvcStampLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SVC_STAMP_LOG
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    int updateByExampleSelective(@Param("record") SvcStampLog record, @Param("example") SvcStampLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SVC_STAMP_LOG
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    int updateByExample(@Param("record") SvcStampLog record, @Param("example") SvcStampLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SVC_STAMP_LOG
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    int updateByPrimaryKeySelective(SvcStampLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SVC_STAMP_LOG
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    int updateByPrimaryKey(SvcStampLog record);
}