package com.jc.pico.mapper;

import com.jc.pico.bean.SvcSalesItemOpt;
import com.jc.pico.bean.SvcSalesItemOptExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SvcSalesItemOptMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_sales_item_opt
     *
     * @mbggenerated Mon Dec 26 10:42:58 KST 2016
     */
    int countByExample(SvcSalesItemOptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_sales_item_opt
     *
     * @mbggenerated Mon Dec 26 10:42:58 KST 2016
     */
    int deleteByExample(SvcSalesItemOptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_sales_item_opt
     *
     * @mbggenerated Mon Dec 26 10:42:58 KST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_sales_item_opt
     *
     * @mbggenerated Mon Dec 26 10:42:58 KST 2016
     */
    int insert(SvcSalesItemOpt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_sales_item_opt
     *
     * @mbggenerated Mon Dec 26 10:42:58 KST 2016
     */
    int insertSelective(SvcSalesItemOpt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_sales_item_opt
     *
     * @mbggenerated Mon Dec 26 10:42:58 KST 2016
     */
    List<SvcSalesItemOpt> selectByExampleWithRowbounds(SvcSalesItemOptExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_sales_item_opt
     *
     * @mbggenerated Mon Dec 26 10:42:58 KST 2016
     */
    List<SvcSalesItemOpt> selectByExample(SvcSalesItemOptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_sales_item_opt
     *
     * @mbggenerated Mon Dec 26 10:42:58 KST 2016
     */
    SvcSalesItemOpt selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_sales_item_opt
     *
     * @mbggenerated Mon Dec 26 10:42:58 KST 2016
     */
    int updateByExampleSelective(@Param("record") SvcSalesItemOpt record, @Param("example") SvcSalesItemOptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_sales_item_opt
     *
     * @mbggenerated Mon Dec 26 10:42:58 KST 2016
     */
    int updateByExample(@Param("record") SvcSalesItemOpt record, @Param("example") SvcSalesItemOptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_sales_item_opt
     *
     * @mbggenerated Mon Dec 26 10:42:58 KST 2016
     */
    int updateByPrimaryKeySelective(SvcSalesItemOpt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_sales_item_opt
     *
     * @mbggenerated Mon Dec 26 10:42:58 KST 2016
     */
    int updateByPrimaryKey(SvcSalesItemOpt record);
}