package com.jc.pico.mapper;

import com.jc.pico.bean.SvcStampType;
import com.jc.pico.bean.SvcStampTypeExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface SvcStampTypeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SVC_STAMP_TYPE
	 * @mbggenerated  Fri May 20 15:37:02 KST 2016
	 */
	int countByExample(SvcStampTypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SVC_STAMP_TYPE
	 * @mbggenerated  Fri May 20 15:37:02 KST 2016
	 */
	int deleteByExample(SvcStampTypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SVC_STAMP_TYPE
	 * @mbggenerated  Fri May 20 15:37:02 KST 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SVC_STAMP_TYPE
	 * @mbggenerated  Fri May 20 15:37:02 KST 2016
	 */
	int insert(SvcStampType record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SVC_STAMP_TYPE
	 * @mbggenerated  Fri May 20 15:37:02 KST 2016
	 */
	int insertSelective(SvcStampType record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SVC_STAMP_TYPE
	 * @mbggenerated  Fri May 20 15:37:02 KST 2016
	 */
	List<SvcStampType> selectByExampleWithRowbounds(SvcStampTypeExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SVC_STAMP_TYPE
	 * @mbggenerated  Fri May 20 15:37:02 KST 2016
	 */
	List<SvcStampType> selectByExample(SvcStampTypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SVC_STAMP_TYPE
	 * @mbggenerated  Fri May 20 15:37:02 KST 2016
	 */
	SvcStampType selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SVC_STAMP_TYPE
	 * @mbggenerated  Fri May 20 15:37:02 KST 2016
	 */
	int updateByExampleSelective(@Param("record") SvcStampType record, @Param("example") SvcStampTypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SVC_STAMP_TYPE
	 * @mbggenerated  Fri May 20 15:37:02 KST 2016
	 */
	int updateByExample(@Param("record") SvcStampType record, @Param("example") SvcStampTypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SVC_STAMP_TYPE
	 * @mbggenerated  Fri May 20 15:37:02 KST 2016
	 */
	int updateByPrimaryKeySelective(SvcStampType record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SVC_STAMP_TYPE
	 * @mbggenerated  Fri May 20 15:37:02 KST 2016
	 */
	int updateByPrimaryKey(SvcStampType record);
}