package com.jc.pico.mapper;

import com.jc.pico.bean.SvcSmsTemplate;
import com.jc.pico.bean.SvcSmsTemplateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SvcSmsTemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SVC_SMS_TEMPLATE
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    int countByExample(SvcSmsTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SVC_SMS_TEMPLATE
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    int deleteByExample(SvcSmsTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SVC_SMS_TEMPLATE
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SVC_SMS_TEMPLATE
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    int insert(SvcSmsTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SVC_SMS_TEMPLATE
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    int insertSelective(SvcSmsTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SVC_SMS_TEMPLATE
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    List<SvcSmsTemplate> selectByExampleWithRowbounds(SvcSmsTemplateExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SVC_SMS_TEMPLATE
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    List<SvcSmsTemplate> selectByExample(SvcSmsTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SVC_SMS_TEMPLATE
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    SvcSmsTemplate selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SVC_SMS_TEMPLATE
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    int updateByExampleSelective(@Param("record") SvcSmsTemplate record, @Param("example") SvcSmsTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SVC_SMS_TEMPLATE
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    int updateByExample(@Param("record") SvcSmsTemplate record, @Param("example") SvcSmsTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SVC_SMS_TEMPLATE
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    int updateByPrimaryKeySelective(SvcSmsTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SVC_SMS_TEMPLATE
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    int updateByPrimaryKey(SvcSmsTemplate record);
}