package com.jc.pico.mapper;

import com.jc.pico.bean.SvcSmsLog;
import com.jc.pico.bean.SvcSmsLogExample;
import com.jc.pico.bean.SvcSmsLogWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SvcSmsLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_sms_log
     *
     * @mbggenerated Tue Aug 30 19:57:04 KST 2016
     */
    int countByExample(SvcSmsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_sms_log
     *
     * @mbggenerated Tue Aug 30 19:57:04 KST 2016
     */
    int deleteByExample(SvcSmsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_sms_log
     *
     * @mbggenerated Tue Aug 30 19:57:04 KST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_sms_log
     *
     * @mbggenerated Tue Aug 30 19:57:04 KST 2016
     */
    int insert(SvcSmsLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_sms_log
     *
     * @mbggenerated Tue Aug 30 19:57:04 KST 2016
     */
    int insertSelective(SvcSmsLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_sms_log
     *
     * @mbggenerated Tue Aug 30 19:57:04 KST 2016
     */
    List<SvcSmsLogWithBLOBs> selectByExampleWithBLOBsWithRowbounds(SvcSmsLogExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_sms_log
     *
     * @mbggenerated Tue Aug 30 19:57:04 KST 2016
     */
    List<SvcSmsLogWithBLOBs> selectByExampleWithBLOBs(SvcSmsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_sms_log
     *
     * @mbggenerated Tue Aug 30 19:57:04 KST 2016
     */
    List<SvcSmsLog> selectByExampleWithRowbounds(SvcSmsLogExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_sms_log
     *
     * @mbggenerated Tue Aug 30 19:57:04 KST 2016
     */
    List<SvcSmsLog> selectByExample(SvcSmsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_sms_log
     *
     * @mbggenerated Tue Aug 30 19:57:04 KST 2016
     */
    SvcSmsLogWithBLOBs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_sms_log
     *
     * @mbggenerated Tue Aug 30 19:57:04 KST 2016
     */
    int updateByExampleSelective(@Param("record") SvcSmsLogWithBLOBs record, @Param("example") SvcSmsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_sms_log
     *
     * @mbggenerated Tue Aug 30 19:57:04 KST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") SvcSmsLogWithBLOBs record, @Param("example") SvcSmsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_sms_log
     *
     * @mbggenerated Tue Aug 30 19:57:04 KST 2016
     */
    int updateByExample(@Param("record") SvcSmsLog record, @Param("example") SvcSmsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_sms_log
     *
     * @mbggenerated Tue Aug 30 19:57:04 KST 2016
     */
    int updateByPrimaryKeySelective(SvcSmsLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_sms_log
     *
     * @mbggenerated Tue Aug 30 19:57:04 KST 2016
     */
    int updateByPrimaryKeyWithBLOBs(SvcSmsLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_sms_log
     *
     * @mbggenerated Tue Aug 30 19:57:04 KST 2016
     */
    int updateByPrimaryKey(SvcSmsLog record);
}