package com.jc.pico.mapper;

import com.jc.pico.bean.SvcStamp;
import com.jc.pico.bean.SvcStampExample;
import com.jc.pico.bean.SvcStampWithBLOBs;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface SvcStampMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SVC_STAMP
	 * @mbggenerated  Fri May 20 15:37:02 KST 2016
	 */
	int countByExample(SvcStampExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SVC_STAMP
	 * @mbggenerated  Fri May 20 15:37:02 KST 2016
	 */
	int deleteByExample(SvcStampExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SVC_STAMP
	 * @mbggenerated  Fri May 20 15:37:02 KST 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SVC_STAMP
	 * @mbggenerated  Fri May 20 15:37:02 KST 2016
	 */
	int insert(SvcStampWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SVC_STAMP
	 * @mbggenerated  Fri May 20 15:37:02 KST 2016
	 */
	int insertSelective(SvcStampWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SVC_STAMP
	 * @mbggenerated  Fri May 20 15:37:02 KST 2016
	 */
	List<SvcStampWithBLOBs> selectByExampleWithBLOBsWithRowbounds(SvcStampExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SVC_STAMP
	 * @mbggenerated  Fri May 20 15:37:02 KST 2016
	 */
	List<SvcStampWithBLOBs> selectByExampleWithBLOBs(SvcStampExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SVC_STAMP
	 * @mbggenerated  Fri May 20 15:37:02 KST 2016
	 */
	List<SvcStamp> selectByExampleWithRowbounds(SvcStampExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SVC_STAMP
	 * @mbggenerated  Fri May 20 15:37:02 KST 2016
	 */
	List<SvcStamp> selectByExample(SvcStampExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SVC_STAMP
	 * @mbggenerated  Fri May 20 15:37:02 KST 2016
	 */
	SvcStampWithBLOBs selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SVC_STAMP
	 * @mbggenerated  Fri May 20 15:37:02 KST 2016
	 */
	int updateByExampleSelective(@Param("record") SvcStampWithBLOBs record, @Param("example") SvcStampExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SVC_STAMP
	 * @mbggenerated  Fri May 20 15:37:02 KST 2016
	 */
	int updateByExampleWithBLOBs(@Param("record") SvcStampWithBLOBs record, @Param("example") SvcStampExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SVC_STAMP
	 * @mbggenerated  Fri May 20 15:37:02 KST 2016
	 */
	int updateByExample(@Param("record") SvcStamp record, @Param("example") SvcStampExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SVC_STAMP
	 * @mbggenerated  Fri May 20 15:37:02 KST 2016
	 */
	int updateByPrimaryKeySelective(SvcStampWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SVC_STAMP
	 * @mbggenerated  Fri May 20 15:37:02 KST 2016
	 */
	int updateByPrimaryKeyWithBLOBs(SvcStampWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SVC_STAMP
	 * @mbggenerated  Fri May 20 15:37:02 KST 2016
	 */
	int updateByPrimaryKey(SvcStamp record);
}