package com.jc.pico.mapper;

import java.util.HashMap;
import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import com.jc.pico.bean.SvcStorePrinter;
import com.jc.pico.bean.SvcStorePrinterExample;
import com.jc.pico.utils.bean.SingleMap;

public interface SvcStorePrinterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_store_printer
     *
     * @mbggenerated Fri Dec 23 11:41:46 KST 2016
     */
    int countByExample(SvcStorePrinterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_store_printer
     *
     * @mbggenerated Fri Dec 23 11:41:46 KST 2016
     */
    int deleteByExample(SvcStorePrinterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_store_printer
     *
     * @mbggenerated Fri Dec 23 11:41:46 KST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_store_printer
     *
     * @mbggenerated Fri Dec 23 11:41:46 KST 2016
     */
    int insert(SvcStorePrinter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_store_printer
     *
     * @mbggenerated Fri Dec 23 11:41:46 KST 2016
     */
    int insertSelective(SvcStorePrinter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_store_printer
     *
     * @mbggenerated Fri Dec 23 11:41:46 KST 2016
     */
    List<SvcStorePrinter> selectByExampleWithRowbounds(SvcStorePrinterExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_store_printer
     *
     * @mbggenerated Fri Dec 23 11:41:46 KST 2016
     */
    List<SvcStorePrinter> selectByExample(SvcStorePrinterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_store_printer
     *
     * @mbggenerated Fri Dec 23 11:41:46 KST 2016
     */
    SvcStorePrinter selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_store_printer
     *
     * @mbggenerated Fri Dec 23 11:41:46 KST 2016
     */
    int updateByExampleSelective(@Param("record") SvcStorePrinter record, @Param("example") SvcStorePrinterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_store_printer
     *
     * @mbggenerated Fri Dec 23 11:41:46 KST 2016
     */
    int updateByExample(@Param("record") SvcStorePrinter record, @Param("example") SvcStorePrinterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_store_printer
     *
     * @mbggenerated Fri Dec 23 11:41:46 KST 2016
     */
    int updateByPrimaryKeySelective(SvcStorePrinter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_store_printer
     *
     * @mbggenerated Fri Dec 23 11:41:46 KST 2016
     */
    int updateByPrimaryKey(SvcStorePrinter record);
    
    
    /**
     * 추가 : 
     *   
     *   밴 연동 ID(상점 머천트 Id)
     *   주방 프린터 정보
     */
    SvcStorePrinter selectByMerchantAndPrinter(HashMap storeInfo);

	boolean updateBySingleMap(SingleMap map);
    
}