package com.jc.pico.mapper;

import com.jc.pico.bean.SvcStockAdjust;
import com.jc.pico.bean.SvcStockAdjustExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SvcStockAdjustMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_stock_adjust
     *
     * @mbggenerated Thu Dec 01 15:37:25 KST 2016
     */
    int countByExample(SvcStockAdjustExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_stock_adjust
     *
     * @mbggenerated Thu Dec 01 15:37:25 KST 2016
     */
    int deleteByExample(SvcStockAdjustExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_stock_adjust
     *
     * @mbggenerated Thu Dec 01 15:37:25 KST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_stock_adjust
     *
     * @mbggenerated Thu Dec 01 15:37:25 KST 2016
     */
    int insert(SvcStockAdjust record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_stock_adjust
     *
     * @mbggenerated Thu Dec 01 15:37:25 KST 2016
     */
    int insertSelective(SvcStockAdjust record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_stock_adjust
     *
     * @mbggenerated Thu Dec 01 15:37:25 KST 2016
     */
    List<SvcStockAdjust> selectByExampleWithRowbounds(SvcStockAdjustExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_stock_adjust
     *
     * @mbggenerated Thu Dec 01 15:37:25 KST 2016
     */
    List<SvcStockAdjust> selectByExample(SvcStockAdjustExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_stock_adjust
     *
     * @mbggenerated Thu Dec 01 15:37:25 KST 2016
     */
    SvcStockAdjust selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_stock_adjust
     *
     * @mbggenerated Thu Dec 01 15:37:25 KST 2016
     */
    int updateByExampleSelective(@Param("record") SvcStockAdjust record, @Param("example") SvcStockAdjustExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_stock_adjust
     *
     * @mbggenerated Thu Dec 01 15:37:25 KST 2016
     */
    int updateByExample(@Param("record") SvcStockAdjust record, @Param("example") SvcStockAdjustExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_stock_adjust
     *
     * @mbggenerated Thu Dec 01 15:37:25 KST 2016
     */
    int updateByPrimaryKeySelective(SvcStockAdjust record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_stock_adjust
     *
     * @mbggenerated Thu Dec 01 15:37:25 KST 2016
     */
    int updateByPrimaryKey(SvcStockAdjust record);
}