package com.jc.pico.mapper;

import com.jc.pico.bean.SvcStoreAlive;
import com.jc.pico.bean.SvcStoreAliveExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SvcStoreAliveMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_store_alive
     *
     * @mbggenerated Thu Nov 10 14:05:03 KST 2016
     */
    int countByExample(SvcStoreAliveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_store_alive
     *
     * @mbggenerated Thu Nov 10 14:05:03 KST 2016
     */
    int deleteByExample(SvcStoreAliveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_store_alive
     *
     * @mbggenerated Thu Nov 10 14:05:03 KST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_store_alive
     *
     * @mbggenerated Thu Nov 10 14:05:03 KST 2016
     */
    int insert(SvcStoreAlive record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_store_alive
     *
     * @mbggenerated Thu Nov 10 14:05:03 KST 2016
     */
    int insertSelective(SvcStoreAlive record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_store_alive
     *
     * @mbggenerated Thu Nov 10 14:05:03 KST 2016
     */
    List<SvcStoreAlive> selectByExampleWithRowbounds(SvcStoreAliveExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_store_alive
     *
     * @mbggenerated Thu Nov 10 14:05:03 KST 2016
     */
    List<SvcStoreAlive> selectByExample(SvcStoreAliveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_store_alive
     *
     * @mbggenerated Thu Nov 10 14:05:03 KST 2016
     */
    SvcStoreAlive selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_store_alive
     *
     * @mbggenerated Thu Nov 10 14:05:03 KST 2016
     */
    int updateByExampleSelective(@Param("record") SvcStoreAlive record, @Param("example") SvcStoreAliveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_store_alive
     *
     * @mbggenerated Thu Nov 10 14:05:03 KST 2016
     */
    int updateByExample(@Param("record") SvcStoreAlive record, @Param("example") SvcStoreAliveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_store_alive
     *
     * @mbggenerated Thu Nov 10 14:05:03 KST 2016
     */
    int updateByPrimaryKeySelective(SvcStoreAlive record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_store_alive
     *
     * @mbggenerated Thu Nov 10 14:05:03 KST 2016
     */
    int updateByPrimaryKey(SvcStoreAlive record);
}