package com.jc.pico.mapper;

import com.jc.pico.bean.SvcStoreImg;
import com.jc.pico.bean.SvcStoreImgExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SvcStoreImgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SVC_STORE_IMG
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    int countByExample(SvcStoreImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SVC_STORE_IMG
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    int deleteByExample(SvcStoreImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SVC_STORE_IMG
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SVC_STORE_IMG
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    int insert(SvcStoreImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SVC_STORE_IMG
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    int insertSelective(SvcStoreImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SVC_STORE_IMG
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    List<SvcStoreImg> selectByExampleWithRowbounds(SvcStoreImgExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SVC_STORE_IMG
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    List<SvcStoreImg> selectByExample(SvcStoreImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SVC_STORE_IMG
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    SvcStoreImg selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SVC_STORE_IMG
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    int updateByExampleSelective(@Param("record") SvcStoreImg record, @Param("example") SvcStoreImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SVC_STORE_IMG
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    int updateByExample(@Param("record") SvcStoreImg record, @Param("example") SvcStoreImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SVC_STORE_IMG
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    int updateByPrimaryKeySelective(SvcStoreImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SVC_STORE_IMG
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    int updateByPrimaryKey(SvcStoreImg record);
}