package com.jc.pico.mapper;

import com.jc.pico.bean.SvcStoreNvr;
import com.jc.pico.bean.SvcStoreNvrExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SvcStoreNvrMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_store_nvr
     *
     * @mbggenerated Mon Aug 01 09:41:22 KST 2016
     */
    int countByExample(SvcStoreNvrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_store_nvr
     *
     * @mbggenerated Mon Aug 01 09:41:22 KST 2016
     */
    int deleteByExample(SvcStoreNvrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_store_nvr
     *
     * @mbggenerated Mon Aug 01 09:41:22 KST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_store_nvr
     *
     * @mbggenerated Mon Aug 01 09:41:22 KST 2016
     */
    int insert(SvcStoreNvr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_store_nvr
     *
     * @mbggenerated Mon Aug 01 09:41:22 KST 2016
     */
    int insertSelective(SvcStoreNvr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_store_nvr
     *
     * @mbggenerated Mon Aug 01 09:41:22 KST 2016
     */
    List<SvcStoreNvr> selectByExampleWithRowbounds(SvcStoreNvrExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_store_nvr
     *
     * @mbggenerated Mon Aug 01 09:41:22 KST 2016
     */
    List<SvcStoreNvr> selectByExample(SvcStoreNvrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_store_nvr
     *
     * @mbggenerated Mon Aug 01 09:41:22 KST 2016
     */
    SvcStoreNvr selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_store_nvr
     *
     * @mbggenerated Mon Aug 01 09:41:22 KST 2016
     */
    int updateByExampleSelective(@Param("record") SvcStoreNvr record, @Param("example") SvcStoreNvrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_store_nvr
     *
     * @mbggenerated Mon Aug 01 09:41:22 KST 2016
     */
    int updateByExample(@Param("record") SvcStoreNvr record, @Param("example") SvcStoreNvrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_store_nvr
     *
     * @mbggenerated Mon Aug 01 09:41:22 KST 2016
     */
    int updateByPrimaryKeySelective(SvcStoreNvr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_svc_store_nvr
     *
     * @mbggenerated Mon Aug 01 09:41:22 KST 2016
     */
    int updateByPrimaryKey(SvcStoreNvr record);
}