package com.jc.pico.mapper;

import com.jc.pico.bean.SvcTableStatus;
import com.jc.pico.bean.SvcTableStatusExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SvcTableStatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SVC_TABLE_STATUS
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    int countByExample(SvcTableStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SVC_TABLE_STATUS
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    int deleteByExample(SvcTableStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SVC_TABLE_STATUS
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SVC_TABLE_STATUS
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    int insert(SvcTableStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SVC_TABLE_STATUS
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    int insertSelective(SvcTableStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SVC_TABLE_STATUS
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    List<SvcTableStatus> selectByExampleWithRowbounds(SvcTableStatusExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SVC_TABLE_STATUS
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    List<SvcTableStatus> selectByExample(SvcTableStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SVC_TABLE_STATUS
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    SvcTableStatus selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SVC_TABLE_STATUS
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    int updateByExampleSelective(@Param("record") SvcTableStatus record, @Param("example") SvcTableStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SVC_TABLE_STATUS
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    int updateByExample(@Param("record") SvcTableStatus record, @Param("example") SvcTableStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SVC_TABLE_STATUS
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    int updateByPrimaryKeySelective(SvcTableStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SVC_TABLE_STATUS
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    int updateByPrimaryKey(SvcTableStatus record);
}