package com.jc.pico.mapper;

import com.jc.pico.bean.SvcTableSection;
import com.jc.pico.bean.SvcTableSectionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SvcTableSectionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SVC_TABLE_SECTION
     *
     * @mbggenerated Wed Jul 06 14:52:10 KST 2016
     */
    int countByExample(SvcTableSectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SVC_TABLE_SECTION
     *
     * @mbggenerated Wed Jul 06 14:52:10 KST 2016
     */
    int deleteByExample(SvcTableSectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SVC_TABLE_SECTION
     *
     * @mbggenerated Wed Jul 06 14:52:10 KST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SVC_TABLE_SECTION
     *
     * @mbggenerated Wed Jul 06 14:52:10 KST 2016
     */
    int insert(SvcTableSection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SVC_TABLE_SECTION
     *
     * @mbggenerated Wed Jul 06 14:52:10 KST 2016
     */
    int insertSelective(SvcTableSection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SVC_TABLE_SECTION
     *
     * @mbggenerated Wed Jul 06 14:52:10 KST 2016
     */
    List<SvcTableSection> selectByExampleWithRowbounds(SvcTableSectionExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SVC_TABLE_SECTION
     *
     * @mbggenerated Wed Jul 06 14:52:10 KST 2016
     */
    List<SvcTableSection> selectByExample(SvcTableSectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SVC_TABLE_SECTION
     *
     * @mbggenerated Wed Jul 06 14:52:10 KST 2016
     */
    SvcTableSection selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SVC_TABLE_SECTION
     *
     * @mbggenerated Wed Jul 06 14:52:10 KST 2016
     */
    int updateByExampleSelective(@Param("record") SvcTableSection record, @Param("example") SvcTableSectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SVC_TABLE_SECTION
     *
     * @mbggenerated Wed Jul 06 14:52:10 KST 2016
     */
    int updateByExample(@Param("record") SvcTableSection record, @Param("example") SvcTableSectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SVC_TABLE_SECTION
     *
     * @mbggenerated Wed Jul 06 14:52:10 KST 2016
     */
    int updateByPrimaryKeySelective(SvcTableSection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SVC_TABLE_SECTION
     *
     * @mbggenerated Wed Jul 06 14:52:10 KST 2016
     */
    int updateByPrimaryKey(SvcTableSection record);
}