package com.jc.pico.mapper;

import com.jc.pico.bean.UserBookmark;
import com.jc.pico.bean.UserBookmarkExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface UserBookmarkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER_BOOKMARK
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    int countByExample(UserBookmarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER_BOOKMARK
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    int deleteByExample(UserBookmarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER_BOOKMARK
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER_BOOKMARK
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    int insert(UserBookmark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER_BOOKMARK
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    int insertSelective(UserBookmark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER_BOOKMARK
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    List<UserBookmark> selectByExampleWithRowbounds(UserBookmarkExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER_BOOKMARK
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    List<UserBookmark> selectByExample(UserBookmarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER_BOOKMARK
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    UserBookmark selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER_BOOKMARK
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    int updateByExampleSelective(@Param("record") UserBookmark record, @Param("example") UserBookmarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER_BOOKMARK
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    int updateByExample(@Param("record") UserBookmark record, @Param("example") UserBookmarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER_BOOKMARK
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    int updateByPrimaryKeySelective(UserBookmark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER_BOOKMARK
     *
     * @mbggenerated Mon Jul 04 21:07:11 KST 2016
     */
    int updateByPrimaryKey(UserBookmark record);
}