package com.jc.pico.mapper;

import com.jc.pico.bean.UserBackofficeMenu;
import com.jc.pico.bean.UserBackofficeMenuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface UserBackofficeMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_backoffice_menu
     *
     * @mbggenerated Wed Feb 22 18:06:08 KST 2017
     */
    int countByExample(UserBackofficeMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_backoffice_menu
     *
     * @mbggenerated Wed Feb 22 18:06:08 KST 2017
     */
    int deleteByExample(UserBackofficeMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_backoffice_menu
     *
     * @mbggenerated Wed Feb 22 18:06:08 KST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_backoffice_menu
     *
     * @mbggenerated Wed Feb 22 18:06:08 KST 2017
     */
    int insert(UserBackofficeMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_backoffice_menu
     *
     * @mbggenerated Wed Feb 22 18:06:08 KST 2017
     */
    int insertSelective(UserBackofficeMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_backoffice_menu
     *
     * @mbggenerated Wed Feb 22 18:06:08 KST 2017
     */
    List<UserBackofficeMenu> selectByExampleWithRowbounds(UserBackofficeMenuExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_backoffice_menu
     *
     * @mbggenerated Wed Feb 22 18:06:08 KST 2017
     */
    List<UserBackofficeMenu> selectByExample(UserBackofficeMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_backoffice_menu
     *
     * @mbggenerated Wed Feb 22 18:06:08 KST 2017
     */
    UserBackofficeMenu selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_backoffice_menu
     *
     * @mbggenerated Wed Feb 22 18:06:08 KST 2017
     */
    int updateByExampleSelective(@Param("record") UserBackofficeMenu record, @Param("example") UserBackofficeMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_backoffice_menu
     *
     * @mbggenerated Wed Feb 22 18:06:08 KST 2017
     */
    int updateByExample(@Param("record") UserBackofficeMenu record, @Param("example") UserBackofficeMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_backoffice_menu
     *
     * @mbggenerated Wed Feb 22 18:06:08 KST 2017
     */
    int updateByPrimaryKeySelective(UserBackofficeMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_backoffice_menu
     *
     * @mbggenerated Wed Feb 22 18:06:08 KST 2017
     */
    int updateByPrimaryKey(UserBackofficeMenu record);
}